// seed.mjs — Run with: node seed.mjs
// Seeds Daiizen database with Yiwu plastic/daily goods categories and products

import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import * as dotenv from "dotenv";
dotenv.config();

const CDN = "https://d2xsxph8kpxj0f.cloudfront.net/310519663405311158/ebebYjMErshCmhKiJP5h4X";

const CATEGORIES = [
  {
    slug: "plastic-kitchenware",
    nameEn: "Plastic Kitchenware",
    nameEs: "Utensilios de Cocina Plásticos",
    nameTr: "Plastik Mutfak Gereçleri",
    namePt: "Utensílios de Cozinha Plásticos",
    nameAr: "أدوات مطبخ بلاستيكية",
    nameRu: "Пластиковая Кухонная Посуда",
    sortOrder: 1,
  },
  {
    slug: "storage-organizers",
    nameEn: "Storage & Organizers",
    nameEs: "Almacenamiento y Organizadores",
    nameTr: "Depolama ve Düzenleyiciler",
    namePt: "Armazenamento e Organizadores",
    nameAr: "التخزين والمنظمات",
    nameRu: "Хранение и Органайзеры",
    sortOrder: 2,
  },
  {
    slug: "bottles-cups",
    nameEn: "Bottles & Cups",
    nameEs: "Botellas y Vasos",
    nameTr: "Şişeler ve Bardaklar",
    namePt: "Garrafas e Copos",
    nameAr: "زجاجات وأكواب",
    nameRu: "Бутылки и Стаканы",
    sortOrder: 3,
  },
  {
    slug: "daily-essentials",
    nameEn: "Daily Essentials",
    nameEs: "Artículos de Primera Necesidad",
    nameTr: "Günlük Temel Ürünler",
    namePt: "Essenciais do Dia a Dia",
    nameAr: "الضروريات اليومية",
    nameRu: "Товары Первой Необходимости",
    sortOrder: 4,
  },
  {
    slug: "cleaning-supplies",
    nameEn: "Cleaning Supplies",
    nameEs: "Artículos de Limpieza",
    nameTr: "Temizlik Malzemeleri",
    namePt: "Produtos de Limpeza",
    nameAr: "مستلزمات التنظيف",
    nameRu: "Чистящие Средства",
    sortOrder: 5,
  },
];

// Image CDN URLs
const IMG = {
  bowlSet:          `${CDN}/bowl-set_4be0f172.jpg`,
  riceContainer:    `${CDN}/rice-container_ee17208c.jpg`,
  riceContainer2:   `${CDN}/rice-container-2_9e631f5e.jpg`,
  storageContainer: `${CDN}/storage-container_6ff88ecb.jpg`,
  waterBottle:      `${CDN}/water-bottle_57a56003.jpg`,
  waterBottles:     `${CDN}/water-bottles-bulk_3fbcb997.jpg`,
  drawerCart:       `${CDN}/drawer-cart_7361335e.png`,
  drawerOrganizer:  `${CDN}/drawer-organizer_481470dd.jpg`,
};

// Products — 25 Yiwu daily goods
const PRODUCTS = [
  // ── Plastic Kitchenware ────────────────────────────────────────────────────
  {
    categorySlug: "plastic-kitchenware",
    slug: "colorful-bowl-set-5pcs",
    nameEn: "Colorful Plastic Bowl Set (5pcs)",
    nameEs: "Juego de Tazones de Plástico Coloridos (5 piezas)",
    nameTr: "Renkli Plastik Kase Seti (5 Adet)",
    namePt: "Conjunto de Tigelas Plásticas Coloridas (5 peças)",
    nameAr: "مجموعة أوعية بلاستيكية ملونة (5 قطع)",
    nameRu: "Набор Цветных Пластиковых Мисок (5 шт.)",
    descriptionEn: "Stackable food-grade plastic bowls with lids. BPA-free, microwave safe. Perfect for meal prep, leftovers, and food storage. Vibrant colors make kitchen organization fun.",
    priceUsdd: "2.80",
    stock: 500,
    images: [IMG.bowlSet],
    isFeatured: true,
    weight: 0.45,
    tags: ["bowl", "kitchen", "plastic", "food storage", "BPA-free"],
  },
  {
    categorySlug: "plastic-kitchenware",
    slug: "plastic-mixing-bowl-large",
    nameEn: "Large Plastic Mixing Bowl 4L",
    nameEs: "Tazón Grande para Mezclar 4L",
    nameTr: "Büyük Plastik Karıştırma Kasesi 4L",
    namePt: "Tigela Grande para Misturar 4L",
    nameAr: "وعاء خلط بلاستيكي كبير 4 لتر",
    nameRu: "Большая Пластиковая Миска для Смешивания 4л",
    descriptionEn: "Heavy-duty 4-liter mixing bowl. Non-slip base, pour spout, and measurement markings. Ideal for baking, salads, and food preparation. Food-grade PP material.",
    priceUsdd: "1.90",
    stock: 300,
    images: [IMG.bowlSet],
    isFeatured: false,
    weight: 0.35,
    tags: ["bowl", "mixing", "kitchen", "baking"],
  },
  {
    categorySlug: "plastic-kitchenware",
    slug: "plastic-plate-set-6pcs",
    nameEn: "Plastic Dinner Plate Set (6pcs)",
    nameEs: "Juego de Platos de Plástico (6 piezas)",
    nameTr: "Plastik Tabak Seti (6 Adet)",
    namePt: "Conjunto de Pratos Plásticos (6 peças)",
    nameAr: "مجموعة أطباق بلاستيكية (6 قطع)",
    nameRu: "Набор Пластиковых Тарелок (6 шт.)",
    descriptionEn: "Durable round dinner plates in assorted colors. Shatterproof, lightweight, dishwasher safe. Great for outdoor dining, picnics, and everyday use.",
    priceUsdd: "3.20",
    stock: 400,
    images: [IMG.bowlSet],
    isFeatured: true,
    weight: 0.50,
    tags: ["plate", "kitchen", "dining", "outdoor"],
  },
  {
    categorySlug: "plastic-kitchenware",
    slug: "plastic-cutting-board",
    nameEn: "Plastic Cutting Board (3-piece set)",
    nameEs: "Tabla de Cortar de Plástico (3 piezas)",
    nameTr: "Plastik Kesme Tahtası (3'lü Set)",
    namePt: "Tábua de Corte Plástica (conjunto de 3)",
    nameAr: "لوح تقطيع بلاستيكي (مجموعة 3 قطع)",
    nameRu: "Пластиковая Разделочная Доска (набор 3 шт.)",
    descriptionEn: "Color-coded cutting boards for meat, vegetables, and bread. Non-slip grip, easy to clean. BPA-free food-grade plastic. Includes 3 sizes.",
    priceUsdd: "2.50",
    stock: 350,
    images: [IMG.bowlSet],
    isFeatured: false,
    weight: 0.40,
    tags: ["cutting board", "kitchen", "cooking"],
  },
  {
    categorySlug: "plastic-kitchenware",
    slug: "plastic-colander-strainer",
    nameEn: "Plastic Colander / Strainer",
    nameEs: "Colador de Plástico",
    nameTr: "Plastik Süzgeç",
    namePt: "Escorredor de Plástico",
    nameAr: "مصفاة بلاستيكية",
    nameRu: "Пластиковый Дуршлаг",
    descriptionEn: "Multi-purpose kitchen colander with fine mesh holes. Rinse fruits, drain pasta, and wash vegetables. Sturdy handles, stable base. Available in multiple colors.",
    priceUsdd: "1.50",
    stock: 600,
    images: [IMG.bowlSet],
    isFeatured: false,
    weight: 0.25,
    tags: ["colander", "strainer", "kitchen"],
  },

  // ── Storage & Organizers ───────────────────────────────────────────────────
  {
    categorySlug: "storage-organizers",
    slug: "airtight-rice-container-5kg",
    nameEn: "Airtight Rice Storage Container 5kg",
    nameEs: "Contenedor Hermético para Arroz 5kg",
    nameTr: "Hava Geçirmez Pirinç Saklama Kabı 5kg",
    namePt: "Recipiente Hermético para Arroz 5kg",
    nameAr: "حاوية تخزين أرز محكمة الإغلاق 5 كجم",
    nameRu: "Герметичный Контейнер для Риса 5 кг",
    descriptionEn: "Large-capacity airtight container keeps rice, flour, and grains fresh. Transparent body for easy viewing, measuring cup included. Moisture-proof and pest-proof.",
    priceUsdd: "4.50",
    stock: 200,
    images: [IMG.riceContainer],
    isFeatured: true,
    weight: 0.70,
    tags: ["rice", "storage", "airtight", "kitchen", "container"],
  },
  {
    categorySlug: "storage-organizers",
    slug: "food-storage-container-set",
    nameEn: "Food Storage Container Set (8pcs)",
    nameEs: "Juego de Recipientes para Alimentos (8 piezas)",
    nameTr: "Gıda Saklama Kabı Seti (8 Adet)",
    namePt: "Conjunto de Recipientes para Alimentos (8 peças)",
    nameAr: "مجموعة حاويات تخزين الطعام (8 قطع)",
    nameRu: "Набор Контейнеров для Еды (8 шт.)",
    descriptionEn: "Stackable food containers with snap-lock lids. Microwave and freezer safe. Clear body lets you see contents at a glance. Includes 4 sizes for all your storage needs.",
    priceUsdd: "5.80",
    stock: 250,
    images: [IMG.storageContainer],
    isFeatured: true,
    weight: 0.65,
    tags: ["food storage", "container", "airtight", "meal prep"],
  },
  {
    categorySlug: "storage-organizers",
    slug: "3-drawer-storage-cart",
    nameEn: "3-Drawer Plastic Storage Cart",
    nameEs: "Carrito de Almacenamiento con 3 Cajones",
    nameTr: "3 Çekmeceli Plastik Depolama Arabası",
    namePt: "Carrinho de Armazenamento com 3 Gavetas",
    nameAr: "عربة تخزين بلاستيكية بـ 3 أدراج",
    nameRu: "Пластиковая Тумба с 3 Ящиками",
    descriptionEn: "Versatile 3-drawer rolling cart for bedroom, bathroom, or office. Smooth-rolling wheels with lock. Removable drawers for easy cleaning. Holds up to 15kg total.",
    priceUsdd: "12.90",
    stock: 80,
    images: [IMG.drawerCart],
    isFeatured: true,
    weight: 2.50,
    tags: ["drawer", "storage", "organizer", "cart", "bedroom"],
  },
  {
    categorySlug: "storage-organizers",
    slug: "drawer-organizer-set",
    nameEn: "Drawer Organizer Set (6pcs)",
    nameEs: "Juego de Organizadores de Cajón (6 piezas)",
    nameTr: "Çekmece Düzenleyici Seti (6 Adet)",
    namePt: "Conjunto de Organizadores de Gaveta (6 peças)",
    nameAr: "مجموعة منظمات الأدراج (6 قطع)",
    nameRu: "Набор Органайзеров для Ящиков (6 шт.)",
    descriptionEn: "Clear plastic drawer dividers for kitchen utensils, office supplies, or bathroom items. Stackable design, easy to clean. Keeps drawers tidy and organized.",
    priceUsdd: "3.90",
    stock: 300,
    images: [IMG.drawerOrganizer],
    isFeatured: false,
    weight: 0.45,
    tags: ["organizer", "drawer", "storage", "kitchen", "office"],
  },
  {
    categorySlug: "storage-organizers",
    slug: "plastic-storage-box-with-lid",
    nameEn: "Plastic Storage Box with Lid (Large)",
    nameEs: "Caja de Almacenamiento con Tapa (Grande)",
    nameTr: "Kapaklı Plastik Saklama Kutusu (Büyük)",
    namePt: "Caixa de Armazenamento com Tampa (Grande)",
    nameAr: "صندوق تخزين بلاستيكي بغطاء (كبير)",
    nameRu: "Пластиковый Ящик с Крышкой (Большой)",
    descriptionEn: "Durable 30L storage box with secure snap-on lid. Stackable design saves space. Ideal for clothes, toys, books, and seasonal items. Transparent body.",
    priceUsdd: "6.50",
    stock: 150,
    images: [IMG.storageContainer],
    isFeatured: false,
    weight: 1.20,
    tags: ["storage box", "container", "household", "organizing"],
  },
  {
    categorySlug: "storage-organizers",
    slug: "rice-dispenser-container",
    nameEn: "Rice Dispenser Container 10kg",
    nameEs: "Dispensador de Arroz 10kg",
    nameTr: "Pirinç Dispenseri 10kg",
    namePt: "Dispensador de Arroz 10kg",
    nameAr: "موزع أرز 10 كجم",
    nameRu: "Диспенсер для Риса 10 кг",
    descriptionEn: "Automatic rice dispenser with measuring cup function. Keeps rice fresh and dry. Easy-pour spout, transparent window. Suitable for rice, beans, and grains.",
    priceUsdd: "7.20",
    stock: 120,
    images: [IMG.riceContainer2],
    isFeatured: true,
    weight: 1.10,
    tags: ["rice", "dispenser", "storage", "kitchen"],
  },

  // ── Bottles & Cups ─────────────────────────────────────────────────────────
  {
    categorySlug: "bottles-cups",
    slug: "sports-water-bottle-700ml",
    nameEn: "Sports Water Bottle 700ml",
    nameEs: "Botella de Agua Deportiva 700ml",
    nameTr: "Spor Su Şişesi 700ml",
    namePt: "Garrafa de Água Esportiva 700ml",
    nameAr: "زجاجة ماء رياضية 700 مل",
    nameRu: "Спортивная Бутылка для Воды 700 мл",
    descriptionEn: "BPA-free sports water bottle with push-pull lid. Leak-proof design, wide mouth for easy filling and cleaning. Lightweight and durable for gym, cycling, and outdoor activities.",
    priceUsdd: "1.80",
    stock: 800,
    images: [IMG.waterBottle],
    isFeatured: true,
    weight: 0.18,
    tags: ["water bottle", "sports", "BPA-free", "gym"],
  },
  {
    categorySlug: "bottles-cups",
    slug: "plastic-cups-set-12pcs",
    nameEn: "Plastic Cups Set 12pcs (400ml)",
    nameEs: "Juego de Vasos de Plástico 12 piezas (400ml)",
    nameTr: "Plastik Bardak Seti 12 Adet (400ml)",
    namePt: "Conjunto de Copos Plásticos 12 peças (400ml)",
    nameAr: "مجموعة أكواب بلاستيكية 12 قطعة (400 مل)",
    nameRu: "Набор Пластиковых Стаканов 12 шт. (400 мл)",
    descriptionEn: "Reusable transparent plastic cups. Shatterproof, stackable, dishwasher safe. Perfect for parties, picnics, and everyday use. Lightweight and easy to carry.",
    priceUsdd: "2.20",
    stock: 600,
    images: [IMG.waterBottles],
    isFeatured: false,
    weight: 0.30,
    tags: ["cups", "plastic", "reusable", "party"],
  },
  {
    categorySlug: "bottles-cups",
    slug: "insulated-water-bottle-500ml",
    nameEn: "Insulated Water Bottle 500ml",
    nameEs: "Botella de Agua Aislada 500ml",
    nameTr: "Yalıtımlı Su Şişesi 500ml",
    namePt: "Garrafa de Água Isolada 500ml",
    nameAr: "زجاجة ماء عازلة 500 مل",
    nameRu: "Термобутылка 500 мл",
    descriptionEn: "Double-wall insulated bottle keeps drinks cold 24h or hot 12h. Leak-proof flip lid. BPA-free food-grade material. Fits standard cup holders.",
    priceUsdd: "3.50",
    stock: 400,
    images: [IMG.waterBottle],
    isFeatured: true,
    weight: 0.22,
    tags: ["insulated", "water bottle", "thermal", "BPA-free"],
  },
  {
    categorySlug: "bottles-cups",
    slug: "plastic-kettle-1-5l",
    nameEn: "Plastic Water Kettle 1.5L",
    nameEs: "Jarra de Agua de Plástico 1.5L",
    nameTr: "Plastik Su Sürahisi 1.5L",
    namePt: "Jarra de Água Plástica 1.5L",
    nameAr: "إبريق ماء بلاستيكي 1.5 لتر",
    nameRu: "Пластиковый Кувшин для Воды 1.5 л",
    descriptionEn: "Transparent water pitcher with filter lid. Easy-pour spout with drip-free design. Keeps water fresh and cool. Perfect for refrigerator storage.",
    priceUsdd: "2.90",
    stock: 280,
    images: [IMG.waterBottles],
    isFeatured: false,
    weight: 0.35,
    tags: ["kettle", "pitcher", "water", "kitchen"],
  },

  // ── Daily Essentials ───────────────────────────────────────────────────────
  {
    categorySlug: "daily-essentials",
    slug: "plastic-laundry-basket",
    nameEn: "Plastic Laundry Basket (Large)",
    nameEs: "Cesto de Ropa Plástico (Grande)",
    nameTr: "Plastik Çamaşır Sepeti (Büyük)",
    namePt: "Cesto de Roupa Plástico (Grande)",
    nameAr: "سلة غسيل بلاستيكية (كبيرة)",
    nameRu: "Пластиковая Корзина для Белья (Большая)",
    descriptionEn: "Ventilated laundry basket with handles. Lightweight yet sturdy. Oval shape fits in tight spaces. Suitable for laundry, toys, and general storage. 40L capacity.",
    priceUsdd: "4.20",
    stock: 200,
    images: [IMG.drawerCart],
    isFeatured: false,
    weight: 0.90,
    tags: ["laundry", "basket", "storage", "household"],
  },
  {
    categorySlug: "daily-essentials",
    slug: "plastic-hangers-10pcs",
    nameEn: "Plastic Clothes Hangers (10pcs)",
    nameEs: "Perchas de Plástico (10 piezas)",
    nameTr: "Plastik Elbise Askısı (10 Adet)",
    namePt: "Cabides de Plástico (10 peças)",
    nameAr: "علاقات ملابس بلاستيكية (10 قطع)",
    nameRu: "Пластиковые Вешалки для Одежды (10 шт.)",
    descriptionEn: "Slim-profile plastic hangers save closet space. Non-slip shoulder design. Strong enough for heavy coats. Available in white, black, and assorted colors. Pack of 10.",
    priceUsdd: "1.20",
    stock: 1000,
    images: [IMG.drawerOrganizer],
    isFeatured: false,
    weight: 0.30,
    tags: ["hangers", "clothes", "closet", "household"],
  },
  {
    categorySlug: "daily-essentials",
    slug: "plastic-trash-can-10l",
    nameEn: "Plastic Trash Can 10L with Lid",
    nameEs: "Papelera de Plástico 10L con Tapa",
    nameTr: "Kapaklı Plastik Çöp Kovası 10L",
    namePt: "Lixeira Plástica 10L com Tampa",
    nameAr: "سلة مهملات بلاستيكية 10 لتر مع غطاء",
    nameRu: "Пластиковое Мусорное Ведро 10 л с Крышкой",
    descriptionEn: "Compact 10L waste bin with flip-top lid. Slim design fits in small spaces. Easy to clean, odor-resistant. Suitable for bedroom, bathroom, and office.",
    priceUsdd: "2.60",
    stock: 350,
    images: [IMG.drawerCart],
    isFeatured: false,
    weight: 0.55,
    tags: ["trash can", "waste bin", "household", "bathroom"],
  },
  {
    categorySlug: "daily-essentials",
    slug: "plastic-shoe-rack-3-tier",
    nameEn: "3-Tier Plastic Shoe Rack",
    nameEs: "Zapatero de Plástico de 3 Niveles",
    nameTr: "3 Katlı Plastik Ayakkabılık",
    namePt: "Sapateira Plástica de 3 Andares",
    nameAr: "رف أحذية بلاستيكي 3 طوابق",
    nameRu: "Пластиковая Полка для Обуви 3 Яруса",
    descriptionEn: "Stackable shoe rack organizer. Holds up to 9 pairs of shoes. Easy assembly, no tools required. Space-saving design for entryway, closet, or bedroom.",
    priceUsdd: "5.90",
    stock: 150,
    images: [IMG.drawerCart],
    isFeatured: true,
    weight: 1.30,
    tags: ["shoe rack", "organizer", "storage", "household"],
  },
  {
    categorySlug: "daily-essentials",
    slug: "plastic-soap-dispenser",
    nameEn: "Plastic Soap Dispenser 300ml",
    nameEs: "Dispensador de Jabón de Plástico 300ml",
    nameTr: "Plastik Sabunluk 300ml",
    namePt: "Dispensador de Sabão Plástico 300ml",
    nameAr: "موزع صابون بلاستيكي 300 مل",
    nameRu: "Пластиковый Дозатор для Мыла 300 мл",
    descriptionEn: "Pump soap dispenser for kitchen or bathroom. Leak-proof pump mechanism, wide opening for easy refilling. Suitable for liquid soap, lotion, and sanitizer.",
    priceUsdd: "1.60",
    stock: 500,
    images: [IMG.bowlSet],
    isFeatured: false,
    weight: 0.15,
    tags: ["soap dispenser", "bathroom", "kitchen", "hygiene"],
  },

  // ── Cleaning Supplies ──────────────────────────────────────────────────────
  {
    categorySlug: "cleaning-supplies",
    slug: "plastic-mop-bucket",
    nameEn: "Plastic Mop Bucket with Wringer",
    nameEs: "Cubo de Fregona con Escurridor",
    nameTr: "Sıkacaklı Plastik Paspas Kovası",
    namePt: "Balde de Esfregona com Espremedor",
    nameAr: "دلو مبلل بلاستيكي مع عاصرة",
    nameRu: "Пластиковое Ведро для Швабры с Отжимом",
    descriptionEn: "15L mop bucket with built-in wringer. Foot pedal for hands-free wringing. Durable plastic construction, easy to clean. Includes drain hole for quick emptying.",
    priceUsdd: "8.50",
    stock: 100,
    images: [IMG.drawerCart],
    isFeatured: false,
    weight: 1.80,
    tags: ["mop", "bucket", "cleaning", "household"],
  },
  {
    categorySlug: "cleaning-supplies",
    slug: "dish-drying-rack",
    nameEn: "Plastic Dish Drying Rack",
    nameEs: "Escurridor de Platos de Plástico",
    nameTr: "Plastik Bulaşık Kurutma Rafı",
    namePt: "Escorredor de Pratos Plástico",
    nameAr: "رف تجفيف الأطباق البلاستيكي",
    nameRu: "Пластиковая Сушилка для Посуды",
    descriptionEn: "Two-tier dish drying rack with drip tray. Holds plates, bowls, cups, and utensils. Rust-resistant, easy to clean. Compact design for small kitchens.",
    priceUsdd: "4.80",
    stock: 200,
    images: [IMG.bowlSet],
    isFeatured: true,
    weight: 0.80,
    tags: ["dish rack", "drying", "kitchen", "organizer"],
  },
  {
    categorySlug: "cleaning-supplies",
    slug: "plastic-brush-set-3pcs",
    nameEn: "Plastic Cleaning Brush Set (3pcs)",
    nameEs: "Juego de Cepillos de Limpieza (3 piezas)",
    nameTr: "Plastik Temizlik Fırçası Seti (3 Adet)",
    namePt: "Conjunto de Escovas de Limpeza (3 peças)",
    nameAr: "مجموعة فرش تنظيف بلاستيكية (3 قطع)",
    nameRu: "Набор Пластиковых Щёток для Уборки (3 шт.)",
    descriptionEn: "Multi-purpose cleaning brush set: bottle brush, dish brush, and vegetable brush. Durable bristles, comfortable grip handles. Suitable for kitchen and bathroom cleaning.",
    priceUsdd: "1.90",
    stock: 600,
    images: [IMG.drawerOrganizer],
    isFeatured: false,
    weight: 0.20,
    tags: ["brush", "cleaning", "kitchen", "household"],
  },
  {
    categorySlug: "cleaning-supplies",
    slug: "plastic-basin-washbowl",
    nameEn: "Plastic Wash Basin 8L",
    nameEs: "Palangana de Plástico 8L",
    nameTr: "Plastik Leğen 8L",
    namePt: "Bacia de Plástico 8L",
    nameAr: "حوض غسيل بلاستيكي 8 لتر",
    nameRu: "Пластиковый Таз 8 л",
    descriptionEn: "Multi-purpose plastic wash basin for laundry, cleaning, and food prep. Oval shape with sturdy handles. Lightweight and durable. Available in multiple colors.",
    priceUsdd: "1.40",
    stock: 700,
    images: [IMG.bowlSet],
    isFeatured: false,
    weight: 0.40,
    tags: ["basin", "washbowl", "laundry", "cleaning"],
  },
];

async function seed() {
  const conn = await mysql.createConnection(process.env.DATABASE_URL);
  const db = drizzle(conn);

  console.log("🌱 Seeding categories...");
  for (const cat of CATEGORIES) {
    await conn.execute(
      `INSERT INTO categories (slug, nameEn, nameEs, nameTr, namePt, nameAr, nameRu, sortOrder, createdAt)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW())
       ON DUPLICATE KEY UPDATE nameEn=VALUES(nameEn), nameEs=VALUES(nameEs), nameTr=VALUES(nameTr),
       namePt=VALUES(namePt), nameAr=VALUES(nameAr), nameRu=VALUES(nameRu), sortOrder=VALUES(sortOrder)`,
      [cat.slug, cat.nameEn, cat.nameEs, cat.nameTr, cat.namePt, cat.nameAr, cat.nameRu, cat.sortOrder]
    );
    console.log(`  ✓ Category: ${cat.nameEn}`);
  }

  console.log("\n🌱 Seeding products...");
  for (const p of PRODUCTS) {
    // Get category id
    const [catRows] = await conn.execute(`SELECT id FROM categories WHERE slug = ?`, [p.categorySlug]);
    const catId = catRows[0]?.id || null;

    const imagesJson = JSON.stringify(p.images);
    const tagsJson = JSON.stringify(p.tags);

    await conn.execute(
      `INSERT INTO products (categoryId, slug, nameEn, nameEs, nameTr, namePt, nameAr, nameRu,
         descriptionEn, priceUsdd, stock, images, tags, isActive, isFeatured, weight, createdAt, updatedAt)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?, NOW(), NOW())
       ON DUPLICATE KEY UPDATE
         categoryId=VALUES(categoryId), nameEn=VALUES(nameEn), nameEs=VALUES(nameEs),
         nameTr=VALUES(nameTr), namePt=VALUES(namePt), nameAr=VALUES(nameAr), nameRu=VALUES(nameRu),
         descriptionEn=VALUES(descriptionEn), priceUsdd=VALUES(priceUsdd), stock=VALUES(stock),
         images=VALUES(images), tags=VALUES(tags), isFeatured=VALUES(isFeatured), weight=VALUES(weight),
         updatedAt=NOW()`,
      [
        catId, p.slug, p.nameEn, p.nameEs, p.nameTr, p.namePt, p.nameAr, p.nameRu,
        p.descriptionEn, p.priceUsdd, p.stock, imagesJson, tagsJson,
        p.isFeatured ? 1 : 0, p.weight || null
      ]
    );
    console.log(`  ✓ Product: ${p.nameEn} — ${p.priceUsdd} USDD`);
  }

  // Seed default exchange rates
  console.log("\n🌱 Seeding exchange rates...");
  const rates = [
    ["USDD", "ARS", 1200],
    ["USDD", "TRY", 32],
    ["USDD", "VES", 36],
    ["USDD", "BRL", 5.1],
    ["USDD", "ZAR", 18.5],
    ["USDD", "NGN", 1600],
    ["USDD", "EGP", 49],
    ["USDD", "PKR", 278],
    ["USDD", "LBP", 89500],
    ["USDD", "IRR", 42000],
  ];
  for (const [base, target, rate] of rates) {
    await conn.execute(
      `INSERT INTO exchangeRates (baseCurrency, targetCurrency, rate, source, fetchedAt)
       VALUES (?, ?, ?, 'seed', NOW())
       ON DUPLICATE KEY UPDATE rate=VALUES(rate), fetchedAt=NOW()`,
      [base, target, rate]
    );
    console.log(`  ✓ Rate: 1 ${base} = ${rate} ${target}`);
  }

  await conn.end();
  console.log("\n✅ Seed complete! 5 categories, 25 products, 10 exchange rates.");
}

seed().catch((e) => { console.error("Seed failed:", e); process.exit(1); });
