import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "es" | "tr" | "pt" | "ar" | "ru";

export const LANGUAGES: { code: Language; label: string; flag: string; dir: "ltr" | "rtl" }[] = [
  { code: "en", label: "English", flag: "🇺🇸", dir: "ltr" },
  { code: "es", label: "Español", flag: "🇦🇷", dir: "ltr" },
  { code: "tr", label: "Türkçe", flag: "🇹🇷", dir: "ltr" },
  { code: "pt", label: "Português", flag: "🇧🇷", dir: "ltr" },
  { code: "ar", label: "العربية", flag: "🇸🇦", dir: "rtl" },
  { code: "ru", label: "Русский", flag: "🇷🇺", dir: "ltr" },
];

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.cart": "Cart",
    "nav.account": "Account",
    "nav.admin": "Admin",
    "nav.login": "Sign In",
    "nav.logout": "Sign Out",
    "nav.search": "Search products...",
    // Hero
    "hero.title": "Quality Goods,\nStable Prices",
    "hero.subtitle": "Shop with USDD stablecoin — your purchasing power protected against inflation.",
    "hero.cta": "Shop Now",
    "hero.learn": "Learn About USDD",
    // Products
    "products.title": "Our Products",
    "products.search": "Search...",
    "products.filter": "Filter",
    "products.all": "All Categories",
    "products.sort": "Sort by",
    "products.sort.newest": "Newest",
    "products.sort.price_asc": "Price: Low to High",
    "products.sort.price_desc": "Price: High to Low",
    "products.empty": "No products found",
    "products.add_cart": "Add to Cart",
    "products.in_stock": "In Stock",
    "products.out_stock": "Out of Stock",
    "products.qty": "Quantity",
    // Cart
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.subtotal": "Subtotal",
    "cart.checkout": "Proceed to Checkout",
    "cart.remove": "Remove",
    "cart.continue": "Continue Shopping",
    // Orders
    "orders.title": "My Orders",
    "orders.empty": "No orders yet",
    "orders.number": "Order",
    "orders.status.pending_payment": "Pending Payment",
    "orders.status.paid": "Paid",
    "orders.status.shipped": "Shipped",
    "orders.status.completed": "Completed",
    "orders.status.cancelled": "Cancelled",
    "orders.total": "Total",
    "orders.date": "Date",
    "orders.view": "View Details",
    // Payment
    "payment.title": "Payment",
    "payment.method": "Pay with USDD",
    "payment.address": "Payment Address",
    "payment.amount": "Amount Due",
    "payment.confirm": "Confirm Payment Sent",
    "payment.confirm_btn": "I've Sent the Payment",
    "payment.waiting": "Waiting for confirmation...",
    "payment.success": "Payment Confirmed!",
    "payment.network": "Network",
    "payment.exact_amount": "Send Exactly This Amount",
    "payment.instructions": "Payment Instructions",
    // Checkout
    "checkout.title": "Checkout",
    "checkout.address": "Delivery Address",
    "checkout.new_address": "Add New Address",
    "checkout.notes": "Order Notes (optional)",
    "checkout.summary": "Order Summary",
    "checkout.place_order": "Place Order",
    // Address fields
    "address.name": "Full Name",
    "address.phone": "Phone",
    "address.country": "Country",
    "address.city": "City",
    "address.state": "State / Province",
    "address.line1": "Address Line 1",
    "address.line2": "Address Line 2 (optional)",
    "address.postal": "Postal Code",
    // Orders
    "orders.items": "Items",
    "cart.total": "Total",
    // Account
    "account.title": "My Account",
    "account.profile": "Profile",
    "account.addresses": "Addresses",
    "account.orders": "Orders",
    "account.save": "Save Changes",
    "account.add_address": "Add Address",
    // Exchange rates
    "rates.title": "Live Exchange Rates",
    "rates.usdd": "1 USDD =",
    "rates.updated": "Updated",
    // Common
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.retry": "Try Again",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.close": "Close",
    "common.back": "Back",
    "common.next": "Next",
    "common.confirm": "Confirm",
    // Chat
    "chat.title": "Customer Support",
    "chat.placeholder": "Ask anything about products, orders, or payments...",
    "chat.send": "Send",
    "chat.greeting": "Hello! I'm Daiizen's AI assistant. How can I help you today?",
  },
  es: {
    "nav.home": "Inicio",
    "nav.products": "Productos",
    "nav.cart": "Carrito",
    "nav.account": "Cuenta",
    "nav.admin": "Admin",
    "nav.login": "Iniciar sesión",
    "nav.logout": "Cerrar sesión",
    "nav.search": "Buscar productos...",
    "hero.title": "Productos de Calidad,\nPrecios Estables",
    "hero.subtitle": "Compra con USDD — tu poder adquisitivo protegido contra la inflación.",
    "hero.cta": "Comprar Ahora",
    "hero.learn": "Conocer USDD",
    "products.title": "Nuestros Productos",
    "products.search": "Buscar...",
    "products.filter": "Filtrar",
    "products.all": "Todas las Categorías",
    "products.sort": "Ordenar por",
    "products.sort.newest": "Más recientes",
    "products.sort.price_asc": "Precio: Menor a Mayor",
    "products.sort.price_desc": "Precio: Mayor a Menor",
    "products.empty": "No se encontraron productos",
    "products.add_cart": "Agregar al Carrito",
    "products.in_stock": "En Stock",
    "products.out_stock": "Sin Stock",
    "products.qty": "Cantidad",
    "cart.title": "Carrito de Compras",
    "cart.empty": "Tu carrito está vacío",
    "cart.subtotal": "Subtotal",
    "cart.checkout": "Proceder al Pago",
    "cart.remove": "Eliminar",
    "cart.continue": "Seguir Comprando",
    "orders.title": "Mis Pedidos",
    "orders.empty": "Sin pedidos aún",
    "orders.number": "Pedido",
    "orders.status.pending_payment": "Pago Pendiente",
    "orders.status.paid": "Pagado",
    "orders.status.shipped": "Enviado",
    "orders.status.completed": "Completado",
    "orders.status.cancelled": "Cancelado",
    "orders.total": "Total",
    "orders.date": "Fecha",
    "orders.view": "Ver Detalles",
    "payment.title": "Pago",
    "payment.method": "Pagar con USDD",
    "payment.address": "Enviar USDD a esta dirección",
    "payment.amount": "Monto",
    "payment.confirm": "Ya envié el pago",
    "payment.waiting": "Esperando confirmación...",
    "payment.success": "¡Pago Confirmado!",
    "account.title": "Mi Cuenta",
    "account.profile": "Perfil",
    "account.addresses": "Direcciones",
    "account.orders": "Pedidos",
    "account.save": "Guardar Cambios",
    "account.add_address": "Agregar Dirección",
    "rates.title": "Tasas de Cambio en Vivo",
    "rates.usdd": "1 USDD =",
    "rates.updated": "Actualizado",
    "common.loading": "Cargando...",
    "common.error": "Algo salió mal",
    "common.retry": "Intentar de nuevo",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.close": "Cerrar",
    "common.back": "Volver",
    "common.next": "Siguiente",
    "common.confirm": "Confirmar",
    "chat.title": "Soporte al Cliente",
    "chat.placeholder": "Pregunta sobre productos, pedidos o pagos...",
    "chat.send": "Enviar",
    "chat.greeting": "¡Hola! Soy el asistente de Daiizen. ¿En qué puedo ayudarte?",
  },
  tr: {
    "nav.home": "Ana Sayfa",
    "nav.products": "Ürünler",
    "nav.cart": "Sepet",
    "nav.account": "Hesap",
    "nav.admin": "Yönetim",
    "nav.login": "Giriş Yap",
    "nav.logout": "Çıkış Yap",
    "nav.search": "Ürün ara...",
    "hero.title": "Kaliteli Ürünler,\nSabit Fiyatlar",
    "hero.subtitle": "USDD ile alışveriş yapın — satın alma gücünüz enflasyona karşı korumalı.",
    "hero.cta": "Alışverişe Başla",
    "hero.learn": "USDD Hakkında",
    "products.title": "Ürünlerimiz",
    "products.search": "Ara...",
    "products.filter": "Filtrele",
    "products.all": "Tüm Kategoriler",
    "products.sort": "Sırala",
    "products.sort.newest": "En Yeni",
    "products.sort.price_asc": "Fiyat: Düşükten Yükseğe",
    "products.sort.price_desc": "Fiyat: Yüksekten Düşüğe",
    "products.empty": "Ürün bulunamadı",
    "products.add_cart": "Sepete Ekle",
    "products.in_stock": "Stokta Var",
    "products.out_stock": "Stok Yok",
    "products.qty": "Miktar",
    "cart.title": "Alışveriş Sepeti",
    "cart.empty": "Sepetiniz boş",
    "cart.subtotal": "Ara Toplam",
    "cart.checkout": "Ödemeye Geç",
    "cart.remove": "Kaldır",
    "cart.continue": "Alışverişe Devam",
    "orders.title": "Siparişlerim",
    "orders.empty": "Henüz sipariş yok",
    "orders.number": "Sipariş",
    "orders.status.pending_payment": "Ödeme Bekleniyor",
    "orders.status.paid": "Ödendi",
    "orders.status.shipped": "Kargoya Verildi",
    "orders.status.completed": "Tamamlandı",
    "orders.status.cancelled": "İptal Edildi",
    "orders.total": "Toplam",
    "orders.date": "Tarih",
    "orders.view": "Detayları Gör",
    "payment.title": "Ödeme",
    "payment.method": "USDD ile Öde",
    "payment.address": "Bu adrese USDD gönderin",
    "payment.amount": "Tutar",
    "payment.confirm": "Ödemeyi gönderdim",
    "payment.waiting": "Onay bekleniyor...",
    "payment.success": "Ödeme Onaylandı!",
    "account.title": "Hesabım",
    "account.profile": "Profil",
    "account.addresses": "Adresler",
    "account.orders": "Siparişler",
    "account.save": "Değişiklikleri Kaydet",
    "account.add_address": "Adres Ekle",
    "rates.title": "Canlı Döviz Kurları",
    "rates.usdd": "1 USDD =",
    "rates.updated": "Güncellendi",
    "common.loading": "Yükleniyor...",
    "common.error": "Bir şeyler ters gitti",
    "common.retry": "Tekrar Dene",
    "common.cancel": "İptal",
    "common.save": "Kaydet",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.close": "Kapat",
    "common.back": "Geri",
    "common.next": "İleri",
    "common.confirm": "Onayla",
    "chat.title": "Müşteri Desteği",
    "chat.placeholder": "Ürünler, siparişler veya ödemeler hakkında soru sorun...",
    "chat.send": "Gönder",
    "chat.greeting": "Merhaba! Ben Daiizen'in AI asistanıyım. Size nasıl yardımcı olabilirim?",
  },
  pt: {
    "nav.home": "Início",
    "nav.products": "Produtos",
    "nav.cart": "Carrinho",
    "nav.account": "Conta",
    "nav.admin": "Admin",
    "nav.login": "Entrar",
    "nav.logout": "Sair",
    "nav.search": "Buscar produtos...",
    "hero.title": "Produtos de Qualidade,\nPreços Estáveis",
    "hero.subtitle": "Compre com USDD — seu poder de compra protegido contra a inflação.",
    "hero.cta": "Comprar Agora",
    "hero.learn": "Saiba sobre USDD",
    "products.title": "Nossos Produtos",
    "products.search": "Buscar...",
    "products.filter": "Filtrar",
    "products.all": "Todas as Categorias",
    "products.sort": "Ordenar por",
    "products.sort.newest": "Mais Recentes",
    "products.sort.price_asc": "Preço: Menor para Maior",
    "products.sort.price_desc": "Preço: Maior para Menor",
    "products.empty": "Nenhum produto encontrado",
    "products.add_cart": "Adicionar ao Carrinho",
    "products.in_stock": "Em Estoque",
    "products.out_stock": "Sem Estoque",
    "products.qty": "Quantidade",
    "cart.title": "Carrinho de Compras",
    "cart.empty": "Seu carrinho está vazio",
    "cart.subtotal": "Subtotal",
    "cart.checkout": "Finalizar Compra",
    "cart.remove": "Remover",
    "cart.continue": "Continuar Comprando",
    "orders.title": "Meus Pedidos",
    "orders.empty": "Nenhum pedido ainda",
    "orders.number": "Pedido",
    "orders.status.pending_payment": "Aguardando Pagamento",
    "orders.status.paid": "Pago",
    "orders.status.shipped": "Enviado",
    "orders.status.completed": "Concluído",
    "orders.status.cancelled": "Cancelado",
    "orders.total": "Total",
    "orders.date": "Data",
    "orders.view": "Ver Detalhes",
    "payment.title": "Pagamento",
    "payment.method": "Pagar com USDD",
    "payment.address": "Envie USDD para este endereço",
    "payment.amount": "Valor",
    "payment.confirm": "Já enviei o pagamento",
    "payment.waiting": "Aguardando confirmação...",
    "payment.success": "Pagamento Confirmado!",
    "account.title": "Minha Conta",
    "account.profile": "Perfil",
    "account.addresses": "Endereços",
    "account.orders": "Pedidos",
    "account.save": "Salvar Alterações",
    "account.add_address": "Adicionar Endereço",
    "rates.title": "Taxas de Câmbio ao Vivo",
    "rates.usdd": "1 USDD =",
    "rates.updated": "Atualizado",
    "common.loading": "Carregando...",
    "common.error": "Algo deu errado",
    "common.retry": "Tentar Novamente",
    "common.cancel": "Cancelar",
    "common.save": "Salvar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.close": "Fechar",
    "common.back": "Voltar",
    "common.next": "Próximo",
    "common.confirm": "Confirmar",
    "chat.title": "Suporte ao Cliente",
    "chat.placeholder": "Pergunte sobre produtos, pedidos ou pagamentos...",
    "chat.send": "Enviar",
    "chat.greeting": "Olá! Sou o assistente de IA da Daiizen. Como posso ajudá-lo hoje?",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.products": "المنتجات",
    "nav.cart": "السلة",
    "nav.account": "الحساب",
    "nav.admin": "الإدارة",
    "nav.login": "تسجيل الدخول",
    "nav.logout": "تسجيل الخروج",
    "nav.search": "ابحث عن المنتجات...",
    "hero.title": "منتجات عالية الجودة،\nأسعار ثابتة",
    "hero.subtitle": "تسوق بعملة USDD المستقرة — قوتك الشرائية محمية من التضخم.",
    "hero.cta": "تسوق الآن",
    "hero.learn": "تعرف على USDD",
    "products.title": "منتجاتنا",
    "products.search": "بحث...",
    "products.filter": "تصفية",
    "products.all": "جميع الفئات",
    "products.sort": "ترتيب حسب",
    "products.sort.newest": "الأحدث",
    "products.sort.price_asc": "السعر: من الأقل للأعلى",
    "products.sort.price_desc": "السعر: من الأعلى للأقل",
    "products.empty": "لم يتم العثور على منتجات",
    "products.add_cart": "أضف إلى السلة",
    "products.in_stock": "متوفر",
    "products.out_stock": "غير متوفر",
    "products.qty": "الكمية",
    "cart.title": "سلة التسوق",
    "cart.empty": "سلتك فارغة",
    "cart.subtotal": "المجموع الفرعي",
    "cart.checkout": "إتمام الشراء",
    "cart.remove": "إزالة",
    "cart.continue": "مواصلة التسوق",
    "orders.title": "طلباتي",
    "orders.empty": "لا توجد طلبات بعد",
    "orders.number": "طلب",
    "orders.status.pending_payment": "في انتظار الدفع",
    "orders.status.paid": "مدفوع",
    "orders.status.shipped": "تم الشحن",
    "orders.status.completed": "مكتمل",
    "orders.status.cancelled": "ملغي",
    "orders.total": "الإجمالي",
    "orders.date": "التاريخ",
    "orders.view": "عرض التفاصيل",
    "payment.title": "الدفع",
    "payment.method": "الدفع بـ USDD",
    "payment.address": "أرسل USDD إلى هذا العنوان",
    "payment.amount": "المبلغ",
    "payment.confirm": "لقد أرسلت الدفعة",
    "payment.waiting": "في انتظار التأكيد...",
    "payment.success": "تم تأكيد الدفع!",
    "account.title": "حسابي",
    "account.profile": "الملف الشخصي",
    "account.addresses": "العناوين",
    "account.orders": "الطلبات",
    "account.save": "حفظ التغييرات",
    "account.add_address": "إضافة عنوان",
    "rates.title": "أسعار الصرف المباشرة",
    "rates.usdd": "1 USDD =",
    "rates.updated": "تم التحديث",
    "common.loading": "جار التحميل...",
    "common.error": "حدث خطأ ما",
    "common.retry": "حاول مجدداً",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.close": "إغلاق",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.confirm": "تأكيد",
    "chat.title": "دعم العملاء",
    "chat.placeholder": "اسأل عن المنتجات أو الطلبات أو المدفوعات...",
    "chat.send": "إرسال",
    "chat.greeting": "مرحباً! أنا مساعد الذكاء الاصطناعي لـ Daiizen. كيف يمكنني مساعدتك اليوم؟",
  },
  ru: {
    "nav.home": "Главная",
    "nav.products": "Товары",
    "nav.cart": "Корзина",
    "nav.account": "Аккаунт",
    "nav.admin": "Админ",
    "nav.login": "Войти",
    "nav.logout": "Выйти",
    "nav.search": "Поиск товаров...",
    "hero.title": "Качественные Товары,\nСтабильные Цены",
    "hero.subtitle": "Покупайте за USDD — ваша покупательная способность защищена от инфляции.",
    "hero.cta": "Купить Сейчас",
    "hero.learn": "Узнать о USDD",
    "products.title": "Наши Товары",
    "products.search": "Поиск...",
    "products.filter": "Фильтр",
    "products.all": "Все Категории",
    "products.sort": "Сортировка",
    "products.sort.newest": "Новинки",
    "products.sort.price_asc": "Цена: по возрастанию",
    "products.sort.price_desc": "Цена: по убыванию",
    "products.empty": "Товары не найдены",
    "products.add_cart": "В Корзину",
    "products.in_stock": "В наличии",
    "products.out_stock": "Нет в наличии",
    "products.qty": "Количество",
    "cart.title": "Корзина",
    "cart.empty": "Ваша корзина пуста",
    "cart.subtotal": "Итого",
    "cart.checkout": "Оформить Заказ",
    "cart.remove": "Удалить",
    "cart.continue": "Продолжить Покупки",
    "orders.title": "Мои Заказы",
    "orders.empty": "Заказов пока нет",
    "orders.number": "Заказ",
    "orders.status.pending_payment": "Ожидает Оплаты",
    "orders.status.paid": "Оплачен",
    "orders.status.shipped": "Отправлен",
    "orders.status.completed": "Завершён",
    "orders.status.cancelled": "Отменён",
    "orders.total": "Итого",
    "orders.date": "Дата",
    "orders.view": "Подробнее",
    "payment.title": "Оплата",
    "payment.method": "Оплатить USDD",
    "payment.address": "Отправьте USDD на этот адрес",
    "payment.amount": "Сумма",
    "payment.confirm": "Я отправил платёж",
    "payment.waiting": "Ожидание подтверждения...",
    "payment.success": "Платёж Подтверждён!",
    "account.title": "Мой Аккаунт",
    "account.profile": "Профиль",
    "account.addresses": "Адреса",
    "account.orders": "Заказы",
    "account.save": "Сохранить Изменения",
    "account.add_address": "Добавить Адрес",
    "rates.title": "Курсы Валют в Реальном Времени",
    "rates.usdd": "1 USDD =",
    "rates.updated": "Обновлено",
    "common.loading": "Загрузка...",
    "common.error": "Что-то пошло не так",
    "common.retry": "Попробовать снова",
    "common.cancel": "Отмена",
    "common.save": "Сохранить",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.close": "Закрыть",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.confirm": "Подтвердить",
    "chat.title": "Служба поддержки",
    "chat.placeholder": "Спросите о товарах, заказах или оплате...",
    "chat.send": "Отправить",
    "chat.greeting": "Привет! Я ИИ-ассистент Daiizen. Чем могу помочь?",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("daiizen-lang");
    return (saved as Language) || "en";
  });

  const currentLang = LANGUAGES.find((l) => l.code === language)!;

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("daiizen-lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = currentLang.dir;
  }, [language, currentLang.dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir: currentLang.dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
