import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "es" | "tr" | "pt" | "ar" | "ru" | "zh";

export const LANGUAGES: { code: Language; label: string; flag: string; dir: "ltr" | "rtl" }[] = [
  { code: "en", label: "English", flag: "🇺🇸", dir: "ltr" },
  { code: "es", label: "Español", flag: "🇦🇷", dir: "ltr" },
  { code: "tr", label: "Türkçe", flag: "🇹🇷", dir: "ltr" },
  { code: "pt", label: "Português", flag: "🇧🇷", dir: "ltr" },
  { code: "ar", label: "العربية", flag: "🇸🇦", dir: "rtl" },
  { code: "ru", label: "Русский", flag: "🇷🇺", dir: "ltr" },
  { code: "zh", label: "中文", flag: "🇨🇳", dir: "ltr" },
];

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.cart": "Cart",
    "nav.account": "Account",
    "nav.admin": "Admin",
    "nav.login": "Sign In",
    "nav.logout": "Sign Out",
    "nav.search": "Search products...",
    // Hero
    "hero.title": "Quality Goods,\nStable Prices",
    "hero.subtitle": "Shop with USDD stablecoin — your purchasing power protected against inflation.",
    "hero.cta": "Shop Now",
    "hero.learn": "Learn About USDD",
    // Products
    "products.title": "Our Products",
    "products.search": "Search...",
    "products.filter": "Filter",
    "products.all": "All Categories",
    "products.sort": "Sort by",
    "products.sort.newest": "Newest",
    "products.sort.price_asc": "Price: Low to High",
    "products.sort.price_desc": "Price: High to Low",
    "products.empty": "No products found",
    "products.add_cart": "Add to Cart",
    "products.in_stock": "In Stock",
    "products.out_stock": "Out of Stock",
    "products.qty": "Quantity",
    // Cart
    "cart.title": "Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.subtotal": "Subtotal",
    "cart.checkout": "Proceed to Checkout",
    "cart.remove": "Remove",
    "cart.continue": "Continue Shopping",
    // Orders
    "orders.title": "My Orders",
    "orders.empty": "No orders yet",
    "orders.number": "Order",
    "orders.status.pending_payment": "Pending Payment",
    "orders.status.paid": "Paid",
    "orders.status.shipped": "Shipped",
    "orders.status.completed": "Completed",
    "orders.status.cancelled": "Cancelled",
    "orders.total": "Total",
    "orders.date": "Date",
    "orders.view": "View Details",
    // Payment
    "payment.title": "Payment",
    "payment.method": "Pay with USDD",
    "payment.address": "Payment Address",
    "payment.amount": "Amount Due",
    "payment.confirm": "Confirm Payment Sent",
    "payment.confirm_btn": "I've Sent the Payment",
    "payment.waiting": "Waiting for confirmation...",
    "payment.success": "Payment Confirmed!",
    "payment.network": "Network",
    "payment.exact_amount": "Send Exactly This Amount",
    "payment.instructions": "Payment Instructions",
    // Checkout
    "checkout.title": "Checkout",
    "checkout.address": "Delivery Address",
    "checkout.new_address": "Add New Address",
    "checkout.notes": "Order Notes (optional)",
    "checkout.summary": "Order Summary",
    "checkout.place_order": "Place Order",
    // Address fields
    "address.name": "Full Name",
    "address.phone": "Phone",
    "address.country": "Country",
    "address.city": "City",
    "address.state": "State / Province",
    "address.line1": "Address Line 1",
    "address.line2": "Address Line 2 (optional)",
    "address.postal": "Postal Code",
    // Orders
    "orders.items": "Items",
    "cart.total": "Total",
    // Account
    "account.title": "My Account",
    "account.profile": "Profile",
    "account.addresses": "Addresses",
    "account.orders": "Orders",
    "account.save": "Save Changes",
    "account.add_address": "Add Address",
    // Exchange rates
    "rates.title": "Live Exchange Rates",
    "rates.usdd": "1 USDD =",
    "rates.updated": "Updated",
    // Common
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.retry": "Try Again",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.close": "Close",
    "common.back": "Back",
    "common.next": "Next",
    "common.confirm": "Confirm",
    // Nav extra
    "nav.marketplace": "Marketplace",
    "nav.open_store": "Open a Store",
    "nav.influencer": "🌟 Influencer / KOL",
    "nav.supply_chain": "🏭 Supply Chain / Brand",
    "nav.seller_dashboard": "📊 Seller Dashboard",
    "nav.referral": "Referral Rewards",
    "nav.my_store": "My Store",
    // Marketplace
    "marketplace.title": "Global Marketplace",
    "marketplace.subtitle": "Discover quality products from global sellers",
    "marketplace.search": "Search products or stores...",
    "marketplace.search_stores": "Search stores by name...",
    "marketplace.products": "Products",
    "marketplace.stores": "Stores",
    "marketplace.all_platforms": "All Platforms",
    "marketplace.no_products": "No products found",
    "marketplace.try_other": "Try other keywords",
    "marketplace.no_stores": "No stores found",
    "marketplace.prev": "Previous",
    "marketplace.next": "Next",
    "marketplace.page_of": "Page {page} of {total}",
    "marketplace.open_store_cta": "Want to open a store on Daiizen?",
    "marketplace.open_store_desc": "Import products from TikTok, Amazon and more. Reach global buyers easily.",
    "marketplace.open_store_btn": "Open a Store",
    "marketplace.platform.all": "All Platforms",
    "marketplace.platform.pinduoduo": "Pinduoduo",
    "marketplace.platform.xiaohongshu": "Xiaohongshu",
    "marketplace.platform.taobao": "Taobao",
    "marketplace.platform.jd": "JD.com",
    "marketplace.platform.other": "Other",
    "marketplace.sort.popular": "Most Popular",
    "marketplace.sort.newest": "Newest",
    "marketplace.sort.price_asc": "Price: Low to High",
    "marketplace.sort.price_desc": "Price: High to Low",
    "marketplace.category": "Category",
    "marketplace.all_categories": "All Categories",
    "marketplace.price_range": "Price Range",
    "marketplace.min_price": "Min Price",
    "marketplace.max_price": "Max Price",
    "marketplace.apply": "Apply",
    // Referral
    "referral.title": "Referral Rewards Center",
    "referral.subtitle": "Invite friends to register and complete their first order. Earn up to 3 levels of rewards (L1: 5% / L2: 2% / L3: 1%)",
    "referral.login_title": "Sign in to view referral rewards",
    "referral.login_desc": "Invite friends to shop and earn up to 3 levels of rewards",
    "referral.login_btn": "Sign In / Register",
    "referral.balance": "Available Balance (USDD)",
    "referral.total_earned": "Total Earned (USDD)",
    "referral.total_referrals": "Total Referrals",
    "referral.pending_rewards": "Pending Rewards",
    "referral.my_link": "My Referral Link",
    "referral.link_desc": "Share with friends. You earn rewards when they complete their first order.",
    "referral.copy": "Copy",
    "referral.copied": "✓ Copied",
    "referral.code": "Referral Code:",
    "referral.rules_title": "Reward Rules",
    "referral.l1": "L1 Direct Referral",
    "referral.l1_desc": "Friends you directly invite complete their first order",
    "referral.l2": "L2 Second Level",
    "referral.l2_desc": "Friends invited by your friends complete their first order",
    "referral.l3": "L3 Third Level",
    "referral.l3_desc": "Third-level connections complete their first order (max 3 levels)",
    "referral.rules_note": "* Rewards are triggered only when referred users complete their first purchase. Max 3 levels. Rewards are issued as platform credits (USDD) and can be used for purchases or withdrawal.",
    "referral.tree_tab": "Referral Tree",
    "referral.rewards_tab": "Reward History",
    "referral.direct": "Direct Referrals",
    "referral.second": "Second Level",
    "referral.third": "Third Level",
    "referral.no_direct": "No direct referrals yet. Share your link to start inviting!",
    "referral.no_second": "No second-level referrals yet",
    "referral.no_third": "No third-level referrals yet",
    "referral.user": "User",
    "referral.purchased": "Purchased",
    "referral.not_purchased": "Not Purchased",
    "referral.no_rewards": "No reward records yet",
    "referral.no_rewards_desc": "Rewards will appear here after your friends complete their first order",
    "referral.from_user": "From user #{id} first order",
    "referral.status.pending": "Pending",
    "referral.status.confirmed": "Confirmed",
    "referral.status.paid": "Paid",
    "referral.status.cancelled": "Cancelled",
    "referral.copied_toast": "Referral link copied!",
    // Onboarding shared
    "onboarding.login_title": "Sign in to start onboarding",
    "onboarding.login_btn": "Sign In / Register",
    "onboarding.already_store": "You already have a store",
    "onboarding.store_name_label": "Store name:",
    "onboarding.active": "Active",
    "onboarding.pending": "Under Review",
    "onboarding.go_seller": "Go to Seller Dashboard",
    "onboarding.browse": "Browse Marketplace",
    "onboarding.deposit_title": "Pay Store Security Deposit",
    "onboarding.no_deposit": "\u2705 No deposit required. Submit for review directly.",
    "onboarding.deposit_amount": "Deposit Amount",
    "onboarding.deposit_note": "The deposit ensures platform transaction security and will be fully refunded upon normal exit.",
    "onboarding.payment_method": "Payment Method: USDD TRC-20",
    "onboarding.deposit_instruction": "Please transfer {amount} USDD to the above address, then enter the transaction hash",
    "onboarding.txhash_label": "Transaction Hash (TxHash)",
    "onboarding.txhash_placeholder": "TRC20 transaction hash",
    "onboarding.submitting": "Submitting...",
    "onboarding.submit_deposit": "Submit Deposit & Await Review",
    "onboarding.submit_apply": "Submit Application",
    "onboarding.submitted_title": "Application Submitted!",
    "onboarding.prev": "Previous",
    "onboarding.next": "Next",
    "onboarding.next_deposit": "Next: Pay Deposit",
    // Influencer onboarding
    "influencer.login_desc": "Become a Daiizen influencer seller. Connect with global supply chains.",
    "influencer.title": "Influencer Seller Onboarding",
    "influencer.subtitle": "Connect with global supply chains. Zero inventory. AI-powered product selection.",
    "influencer.step0": "Choose Type",
    "influencer.step1": "Store Info",
    "influencer.step2": "Social Media",
    "influencer.step3": "Pay Deposit",
    "influencer.step4": "Done",
    "influencer.choose_type": "Choose Onboarding Type",
    "influencer.kol_title": "Influencer / KOL",
    "influencer.kol_desc": "Have followers and want to monetize through product promotion. Select from supply chain, zero inventory, AI-powered product selection.",
    "influencer.kol_badge1": "Zero Inventory",
    "influencer.kol_badge2": "AI Selection",
    "influencer.kol_badge3": "Drop Shipping",
    "influencer.sc_title": "Supply Chain / Brand",
    "influencer.sc_desc": "Have products and want to expand sales through influencer channels. Provide wholesale catalog for influencers to sell.",
    "influencer.sc_badge1": "Wholesale Catalog",
    "influencer.sc_badge2": "Influencer Sales",
    "influencer.sc_badge3": "Drop Ship",
    "influencer.store_info": "Fill in Store Information",
    "influencer.store_name": "Store Name *",
    "influencer.store_name_placeholder": "e.g. Sarah's Favorites",
    "influencer.store_slug": "Store URL Identifier (slug) *",
    "influencer.store_slug_placeholder": "e.g. sarahs-shop (letters, numbers, hyphens only)",
    "influencer.store_url_preview": "Store URL: /store/",
    "influencer.store_desc_label": "Store Description",
    "influencer.store_desc_placeholder": "Describe your store style and main product categories...",
    "influencer.contact_email": "Contact Email",
    "influencer.social_title": "Social Media Accounts (Optional)",
    "influencer.social_desc": "Adding your social media accounts helps increase store credibility and exposure",
    "influencer.tiktok": "\ud83c\udfb5 TikTok / Douyin",
    "influencer.instagram": "\ud83d\udcf8 Instagram",
    "influencer.youtube": "\u25b6\ufe0f YouTube",
    "influencer.xiaohongshu": "\ud83d\udcd5 Xiaohongshu",
    "influencer.followers": "Total Followers (approx.)",
    "influencer.followers_placeholder": "e.g. 50000",
    "influencer.submitted_desc": "Your influencer store application has been submitted. The platform will review it within 1-3 business days. Once approved, you can start selecting products from the supply chain.",
    "influencer.benefit1_title": "Zero Inventory",
    "influencer.benefit1_desc": "Select products directly from supply chains. No stocking needed. Drop shipped to buyers.",
    "influencer.benefit2_title": "AI Product Selection",
    "influencer.benefit2_desc": "AI analyzes trending products and recommends the best items for your audience.",
    "influencer.benefit3_title": "3-Level Referral Rewards",
    "influencer.benefit3_desc": "Invite friends to register and shop. Earn up to 3 levels of referral rewards.",
    // Supply chain onboarding
    "supplychain.login_desc": "Become a Daiizen supply chain partner. Connect with global influencer channels.",
    "supplychain.title": "Supply Chain / Brand Onboarding",
    "supplychain.subtitle": "Upload your wholesale catalog. Let global influencers sell for you. Drop shipping. Easy expansion.",
    "supplychain.step0": "Basic Info",
    "supplychain.step1": "Supply Chain Details",
    "supplychain.step2": "Pay Deposit",
    "supplychain.step3": "Done",
    "supplychain.basic_info": "Fill in Basic Information",
    "supplychain.company_name": "Company / Brand Name *",
    "supplychain.company_name_placeholder": "e.g. Global Wholesale Co.",
    "supplychain.company_desc": "Company Description",
    "supplychain.company_desc_placeholder": "Describe your main product categories and advantages...",
    "supplychain.contact_email": "Contact Email",
    "supplychain.contact_phone": "Contact Phone",
    "supplychain.country": "Company Country / Region",
    "supplychain.country_placeholder": "e.g. China",
    "supplychain.details_title": "Supply Chain Details",
    "supplychain.warehouse": "Warehouse Location",
    "supplychain.warehouse_placeholder": "e.g. China - Yiwu",
    "supplychain.shipping_days": "Average Shipping Days",
    "supplychain.moq": "Minimum Order Quantity (units)",
    "supplychain.moq_placeholder": "1 (enter 1 for drop shipping)",
    "supplychain.moq_note": "Enter 1 if you support drop shipping",
    "supplychain.dropship_title": "\ud83e\udd1d Drop Shipping Partnership",
    "supplychain.dropship_desc": "After onboarding, you can upload your wholesale product catalog (with wholesale prices). Influencers select products and sell at their own prices. When an order is placed, the platform notifies you to ship directly to the buyer. The platform deducts a fee, the supply chain receives the wholesale price, and the influencer earns the margin.",
    "supplychain.submitted_desc": "Your supply chain store application has been submitted. The platform will review it within 1-3 business days. Once approved, you can upload your wholesale product catalog and start collaborating with influencers.",
    "supplychain.benefit1_title": "Global Influencer Channels",
    "supplychain.benefit1_desc": "Access platform influencer resources. Quickly open overseas markets without building your own sales team.",
    "supplychain.benefit2_title": "Drop Shipping",
    "supplychain.benefit2_desc": "Influencers sell, you ship. No inventory risk for influencers. Lower risk for both sides.",
    "supplychain.benefit3_title": "Stable Wholesale Income",
    "supplychain.benefit3_desc": "Receive wholesale price per sale. Platform handles payment settlement. Funds are secure.",
    // Chat
    "chat.title": "Customer Support",
    "chat.placeholder": "Ask anything about products, orders, or payments...",
    "chat.send": "Send",
    "chat.greeting": "Hello! I'm Daiizen's AI assistant. How can I help you today?",
    // Review
    "review.title": "Customer Reviews",
    "review.no_reviews": "No reviews yet. Be the first to review!",
    "review.write": "Write a Review",
    "review.rating": "Rating",
    "review.comment": "Comment (optional)",
    "review.submit": "Submit Review",
    "review.submitting": "Submitting...",
    "review.success": "Review submitted!",
    "review.already": "Already reviewed",
    // Store Product Detail
    "storeproduct.from": "From",
    "storeproduct.units": "units",
    "storeproduct.description": "Description",
    "storeproduct.buy_on": "Buy on",
    "storeproduct.redirect_note": "This product will redirect to the original platform to complete purchase",
    "storeproduct.view_more": "View more products from this store",
    "storeproduct.enter_store": "Visit Store",
    // Seller Dashboard
    "seller.open_store": "Open Your Store",
    "seller.open_store_desc": "Open a store on Daiizen Global Marketplace and reach buyers worldwide",
    "seller.notice_title": "Store Opening Notice",
    "seller.deposit_required": "Security deposit required",
    "seller.deposit_refundable": ", refundable upon exit",
    "seller.platform_fee": "Platform fee",
    "seller.fee_per_order": "per order",
    "seller.review_required": "Store requires admin review before going live",
    "seller.import_note": "Supports importing product links from TikTok, Pinduoduo, Xiaohongshu, Amazon, SHEIN, etc.",
    "seller.store_name": "Store Name *",
    "seller.store_desc": "Store Description",
    "seller.contact_email": "Contact Email",
    "seller.contact_phone": "Contact Phone",
    "seller.country": "Country / Region",
    "seller.deposit_confirmed": "Deposit Confirmed",
    "seller.deposit_pending": "Deposit Pending Confirmation",
    "seller.pay_deposit": "Pay Store Security Deposit",
    "seller.deposit_address": "USDD TRC-20 Receiving Address:",
    "seller.txhash": "Transaction Hash (TxHash)",
    "seller.no_products": "No products yet. Click the button above to add.",
    "seller.prev_page": "Previous",
    "seller.next_page": "Next",
    "seller.add_product": "Add Product",
    "seller.manual_add": "Manual Add",
    "seller.import_link": "Import Link",
    "seller.product_name": "Product Name *",
    "seller.product_desc": "Product Description",
    "seller.price_usdd": "Price (USDD) *",
    "seller.stock": "Stock Quantity",
    "seller.image_urls": "Product Image URLs (one per line)",
    "seller.product_link": "Product Link *",
    "seller.import_placeholder": "Paste product link, e.g. https://www.tiktok.com/...",
    "seller.import_platforms": "Supports TikTok, Pinduoduo, Xiaohongshu, Amazon, SHEIN, Taobao, JD, Lazada, Shopee, etc.",
    "seller.ai_parsing": "AI is parsing product info...",
    "seller.ai_note": "AI will auto-extract name, description, price, etc. You can edit after import.",
    "seller.login_required": "Please sign in first",
    "seller.login_desc": "Sign in to open your store",
    "seller.back_home": "Back to Home",
    "seller.view_store": "View Store Page",
    "seller.under_review": "Store Under Review",
    "seller.review_desc": "Your application is under review. Please pay the deposit first, then wait for admin confirmation.",
    "seller.rejected": "Application Rejected",
    "seller.suspended": "Store Suspended",
    "seller.products_on_sale": "Products on Sale",
    "seller.total_orders": "Total Orders",
    "seller.total_earnings": "Total Earnings",
    "seller.withdraw_btn": "Request Withdrawal →",
    "seller.platform_fee_label": "Platform Fee",
    "seller.products_tab": "Products",
    "seller.settings_tab": "Store Settings",
    "seller.deposit_tab": "Deposit",
    "seller.store_info": "Store Basic Info",
    "seller.store_name_label": "Store Name",
    "seller.store_logo": "Store Logo URL",
    "seller.store_banner": "Store Banner URL",
    "seller.status.pending": "Under Review",
    "seller.status.active": "Active",
    "seller.status.suspended": "Suspended",
    "seller.status.rejected": "Rejected",
    // Admin
    "admin.pending_stores": "Pending Store Applications",
    "admin.no_pending": "No pending store applications",
    "admin.col_store": "Store",
    "admin.col_seller": "Seller",
    "admin.col_applied": "Applied At",
    "admin.col_actions": "Actions",
    "admin.approve": "Approve",
    "admin.reject": "Reject",
    "admin.all_stores": "All Stores",
    "admin.col_status": "Status",
    "admin.col_products": "Products",
    "admin.suspend": "Suspend",
    "admin.restore": "Restore",
    "admin.deposit_mgmt": "Deposit Management",
    "admin.no_deposits": "No pending deposits",
    "admin.col_amount": "Amount",
    "admin.col_txhash": "TxHash",
    "admin.confirm_deposit": "Confirm Receipt",
    "admin.market_config": "Market Platform Config",
    "admin.wallet_address": "Receiving Wallet Address (USDD TRC-20)",
    "admin.payment_config": "Payment Method Config",
    "admin.payment_config_desc": "Configure Alipay, WeChat Pay, UnionPay accounts. Sellers will see these when paying deposit.",
    "admin.configured_methods": "Configured Payment Methods",
    "admin.delete": "Delete",
    "admin.add_payment": "Add / Update Payment Method",
    "admin.payment_type": "Payment Type",
    "admin.alipay": "Alipay",
    "admin.wechat": "WeChat Pay",
    "admin.unionpay": "UnionPay",
    "admin.account_name": "Account Name / Merchant Name",
    "admin.account_number": "Phone / Account Number",
    "admin.qr_url": "QR Code URL (optional)",
    "admin.enable_method": "Enable this payment method",
    "admin.usdd_deposits": "USDD Deposit Review",
    "admin.usdd_deposits_desc": "After users submit deposit requests, admin confirms manually. Balance updates automatically.",
    "admin.no_usdd_deposits": "No pending deposit requests",
    "admin.confirm_deposit_btn": "✓ Confirm Deposit",
    "admin.reject_deposit_btn": "✗ Reject",
    "admin.withdrawals": "Seller Withdrawal Management",
    "admin.no_withdrawals": "No withdrawal requests",
    "admin.approve_withdrawal": "✓ Approve",
    "admin.confirm_paid": "Confirm Paid",
    "admin.cancel": "Cancel",
    "admin.mark_paid": "💸 Mark as Paid",
    "admin.tab_stores": "Store Management",
    "admin.tab_deposit": "Deposit",
    "admin.tab_market": "Market Config",
    "admin.tab_payment": "Payment Config",
    "admin.tab_usdd": "USDD Deposits",
    "admin.tab_withdrawals": "Withdrawals",
    "admin.reject_reason": "Reject reason (optional)",
    "admin.suspend_reason": "Suspend reason",
    "admin.deposit_confirmed_toast": "Deposit confirmed, balance updated",
    "admin.deposit_rejected_toast": "Deposit rejected",
    "admin.withdrawal_approved_toast": "Withdrawal approved",
    "admin.withdrawal_rejected_toast": "Withdrawal rejected, balance refunded",
    "admin.withdrawal_paid_toast": "Marked as paid",
    "admin.payment_updated_toast": "Payment method updated",
    "admin.deleted_toast": "Deleted",
    "admin.store_approved_toast": "Store approved",
    "admin.store_rejected_toast": "Store rejected",
    "admin.store_suspended_toast": "Store suspended",
    "admin.store_restored_toast": "Store restored",
    "admin.deposit_confirmed2_toast": "Deposit confirmed",
    "admin.deposit_rejected2_toast": "Deposit rejected",
    "admin.config_updated_toast": "Config updated",
    // Wallet
    "wallet.title": "USDD Wallet",
    "wallet.balance": "Available Balance",
    "wallet.deposit": "Deposit",
    "wallet.history": "Transaction History",
    "wallet.no_transactions": "No transactions yet",
    "wallet.deposit_title": "Deposit USDD",
    "wallet.deposit_desc": "Transfer USDD (TRC-20 / TRON network) to the address below",
    "wallet.network_warning": "⚠️ Only send USDD on TRC-20 / TRON network. Sending other tokens or using wrong network will result in permanent loss.",
    "wallet.copy_address": "Copy Address",
    "wallet.copied": "Copied!",
    "wallet.submit_deposit": "Submit Deposit Proof",
    "wallet.submit_desc": "After transfer, submit your TxHash for admin confirmation",
    "wallet.txhash_label": "Transaction Hash (TxHash)",
    "wallet.txhash_placeholder": "e.g. abc123...",
    "wallet.amount_label": "Deposit Amount (USDD)",
    "wallet.submit_btn": "Submit for Review",
    "wallet.submitting": "Submitting...",
    "wallet.submitted_toast": "Deposit submitted! Admin will confirm within 24 hours.",
    "wallet.login_required": "Please sign in to view your wallet",
    // Withdrawal
    "withdrawal.title": "Seller Withdrawal",
    "withdrawal.balance": "Available Balance",
    "withdrawal.request": "Request Withdrawal",
    "withdrawal.history": "Withdrawal History",
    "withdrawal.no_history": "No withdrawal records",
    "withdrawal.amount": "Withdrawal Amount (USDD)",
    "withdrawal.wallet": "Receiving Wallet (TRC-20)",
    "withdrawal.wallet_placeholder": "USDD TRC-20 wallet address",
    "withdrawal.note": "Note (optional)",
    "withdrawal.submit": "Submit Withdrawal Request",
    "withdrawal.submitting": "Submitting...",
    "withdrawal.success": "Withdrawal request submitted!",
    "withdrawal.insufficient": "Insufficient balance",
    "withdrawal.login_required": "Please sign in",
    "withdrawal.no_store": "You need a store to withdraw earnings",
    "withdrawal.status.pending": "Pending",
    "withdrawal.status.approved": "Approved",
    "withdrawal.status.rejected": "Rejected",
    "withdrawal.status.paid": "Paid",
    // Common (extra keys)
    "common.coming_soon": "Coming soon",
    "common.saving": "Saving...",
    "common.saved": "Saved!",
    "common.submit": "Submit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.all": "All",
    "common.yes": "Yes",
    "common.no": "No",
    "common.na": "N/A",
    "common.date": "Date",
    "common.amount": "Amount",
    "common.status": "Status",
    "common.actions": "Actions",
    "common.user": "User",
    "common.store": "Store",
    "common.product": "Product",
    "common.order": "Order",
    "common.price": "Price",
    "common.qty": "Qty",
    "common.total": "Total",
    "common.note": "Note",
    "common.reason": "Reason",
    "common.txhash": "TxHash",
    "common.wallet_address": "Wallet Address",
    "common.copy": "Copy",
    "common.copied": "Copied!",
    "common.sign_in": "Sign In",
    "common.sign_up": "Sign Up",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.password": "Password",
    "common.name": "Name",
  },
  es: {
    "nav.home": "Inicio",
    "nav.products": "Productos",
    "nav.cart": "Carrito",
    "nav.account": "Cuenta",
    "nav.admin": "Admin",
    "nav.login": "Iniciar sesión",
    "nav.logout": "Cerrar sesión",
    "nav.search": "Buscar productos...",
    "hero.title": "Productos de Calidad,\nPrecios Estables",
    "hero.subtitle": "Compra con USDD — tu poder adquisitivo protegido contra la inflación.",
    "hero.cta": "Comprar Ahora",
    "hero.learn": "Conocer USDD",
    "products.title": "Nuestros Productos",
    "products.search": "Buscar...",
    "products.filter": "Filtrar",
    "products.all": "Todas las Categorías",
    "products.sort": "Ordenar por",
    "products.sort.newest": "Más recientes",
    "products.sort.price_asc": "Precio: Menor a Mayor",
    "products.sort.price_desc": "Precio: Mayor a Menor",
    "products.empty": "No se encontraron productos",
    "products.add_cart": "Agregar al Carrito",
    "products.in_stock": "En Stock",
    "products.out_stock": "Sin Stock",
    "products.qty": "Cantidad",
    "cart.title": "Carrito de Compras",
    "cart.empty": "Tu carrito está vacío",
    "cart.subtotal": "Subtotal",
    "cart.checkout": "Proceder al Pago",
    "cart.remove": "Eliminar",
    "cart.continue": "Seguir Comprando",
    "orders.title": "Mis Pedidos",
    "orders.empty": "Sin pedidos aún",
    "orders.number": "Pedido",
    "orders.status.pending_payment": "Pago Pendiente",
    "orders.status.paid": "Pagado",
    "orders.status.shipped": "Enviado",
    "orders.status.completed": "Completado",
    "orders.status.cancelled": "Cancelado",
    "orders.total": "Total",
    "orders.date": "Fecha",
    "orders.view": "Ver Detalles",
    "payment.title": "Pago",
    "payment.method": "Pagar con USDD",
    "payment.address": "Enviar USDD a esta dirección",
    "payment.amount": "Monto",
    "payment.confirm": "Ya envié el pago",
    "payment.waiting": "Esperando confirmación...",
    "payment.success": "¡Pago Confirmado!",
    "account.title": "Mi Cuenta",
    "account.profile": "Perfil",
    "account.addresses": "Direcciones",
    "account.orders": "Pedidos",
    "account.save": "Guardar Cambios",
    "account.add_address": "Agregar Dirección",
    "rates.title": "Tasas de Cambio en Vivo",
    "rates.usdd": "1 USDD =",
    "rates.updated": "Actualizado",
    "common.loading": "Cargando...",
    "common.error": "Algo salió mal",
    "common.retry": "Intentar de nuevo",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.close": "Cerrar",
    "common.back": "Volver",
    "common.next": "Siguiente",
    "common.confirm": "Confirmar",
    "chat.title": "Soporte al Cliente",
    "chat.placeholder": "Pregunta sobre productos, pedidos o pagos...",
    "chat.send": "Enviar",
    "chat.greeting": "¡Hola! Soy el asistente de Daiizen. ¿En qué puedo ayudarte?",
    "nav.marketplace": "Mercado Global",
    "nav.open_store": "Abrir Tienda",
    "nav.influencer": "🌟 Influencer / KOL",
    "nav.supply_chain": "🏭 Cadena de Suministro",
    "nav.seller_dashboard": "📊 Panel de Vendedor",
    "nav.referral": "Programa de Referidos",
    "nav.my_store": "Mi Tienda",
    "marketplace.sort.popular": "Más Populares",
    "marketplace.sort.newest": "Más Recientes",
    "marketplace.sort.price_asc": "Precio: Menor a Mayor",
    "marketplace.sort.price_desc": "Precio: Mayor a Menor",
    "marketplace.category": "Categoría",
    "marketplace.all_categories": "Todas las Categorías",
    "marketplace.price_range": "Rango de Precio",
    "marketplace.min_price": "Precio Mín.",
    "marketplace.max_price": "Precio Máx.",
    "marketplace.apply": "Aplicar",
  },
  tr: {
    "nav.home": "Ana Sayfa",
    "nav.products": "Ürünler",
    "nav.cart": "Sepet",
    "nav.account": "Hesap",
    "nav.admin": "Yönetim",
    "nav.login": "Giriş Yap",
    "nav.logout": "Çıkış Yap",
    "nav.search": "Ürün ara...",
    "hero.title": "Kaliteli Ürünler,\nSabit Fiyatlar",
    "hero.subtitle": "USDD ile alışveriş yapın — satın alma gücünüz enflasyona karşı korumalı.",
    "hero.cta": "Alışverişe Başla",
    "hero.learn": "USDD Hakkında",
    "products.title": "Ürünlerimiz",
    "products.search": "Ara...",
    "products.filter": "Filtrele",
    "products.all": "Tüm Kategoriler",
    "products.sort": "Sırala",
    "products.sort.newest": "En Yeni",
    "products.sort.price_asc": "Fiyat: Düşükten Yükseğe",
    "products.sort.price_desc": "Fiyat: Yüksekten Düşüğe",
    "products.empty": "Ürün bulunamadı",
    "products.add_cart": "Sepete Ekle",
    "products.in_stock": "Stokta Var",
    "products.out_stock": "Stok Yok",
    "products.qty": "Miktar",
    "cart.title": "Alışveriş Sepeti",
    "cart.empty": "Sepetiniz boş",
    "cart.subtotal": "Ara Toplam",
    "cart.checkout": "Ödemeye Geç",
    "cart.remove": "Kaldır",
    "cart.continue": "Alışverişe Devam",
    "orders.title": "Siparişlerim",
    "orders.empty": "Henüz sipariş yok",
    "orders.number": "Sipariş",
    "orders.status.pending_payment": "Ödeme Bekleniyor",
    "orders.status.paid": "Ödendi",
    "orders.status.shipped": "Kargoya Verildi",
    "orders.status.completed": "Tamamlandı",
    "orders.status.cancelled": "İptal Edildi",
    "orders.total": "Toplam",
    "orders.date": "Tarih",
    "orders.view": "Detayları Gör",
    "payment.title": "Ödeme",
    "payment.method": "USDD ile Öde",
    "payment.address": "Bu adrese USDD gönderin",
    "payment.amount": "Tutar",
    "payment.confirm": "Ödemeyi gönderdim",
    "payment.waiting": "Onay bekleniyor...",
    "payment.success": "Ödeme Onaylandı!",
    "account.title": "Hesabım",
    "account.profile": "Profil",
    "account.addresses": "Adresler",
    "account.orders": "Siparişler",
    "account.save": "Değişiklikleri Kaydet",
    "account.add_address": "Adres Ekle",
    "rates.title": "Canlı Döviz Kurları",
    "rates.usdd": "1 USDD =",
    "rates.updated": "Güncellendi",
    "common.loading": "Yükleniyor...",
    "common.error": "Bir şeyler ters gitti",
    "common.retry": "Tekrar Dene",
    "common.cancel": "İptal",
    "common.save": "Kaydet",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.close": "Kapat",
    "common.back": "Geri",
    "common.next": "İleri",
    "common.confirm": "Onayla",
    "chat.title": "Müşteri Desteği",
    "chat.placeholder": "Ürünler, siparişler veya ödemeler hakkında soru sorun...",
    "chat.send": "Gönder",
    "chat.greeting": "Merhaba! Ben Daiizen'in AI asistanıyım. Size nasıl yardımcı olabilirim?",
    "nav.marketplace": "Global Pazar",
    "nav.open_store": "Mağaza Aç",
    "nav.influencer": "🌟 Influencer / KOL",
    "nav.supply_chain": "🏭 Tedarik Zinciri",
    "nav.seller_dashboard": "📊 Satıcı Paneli",
    "nav.referral": "Referans Ödülleri",
    "nav.my_store": "Mağazam",
    "marketplace.sort.popular": "En Popüler",
    "marketplace.sort.newest": "En Yeni",
    "marketplace.sort.price_asc": "Fiyat: Düşükten Yüksekğe",
    "marketplace.sort.price_desc": "Fiyat: Yüksekten Düşüğe",
    "marketplace.category": "Kategori",
    "marketplace.all_categories": "Tüm Kategoriler",
    "marketplace.price_range": "Fiyat Aralığı",
    "marketplace.min_price": "Min Fiyat",
    "marketplace.max_price": "Maks Fiyat",
    "marketplace.apply": "Uygula",
  },
  pt: {
    "nav.home": "Início",
    "nav.products": "Produtos",
    "nav.cart": "Carrinho",
    "nav.account": "Conta",
    "nav.admin": "Admin",
    "nav.login": "Entrar",
    "nav.logout": "Sair",
    "nav.search": "Buscar produtos...",
    "hero.title": "Produtos de Qualidade,\nPreços Estáveis",
    "hero.subtitle": "Compre com USDD — seu poder de compra protegido contra a inflação.",
    "hero.cta": "Comprar Agora",
    "hero.learn": "Saiba sobre USDD",
    "products.title": "Nossos Produtos",
    "products.search": "Buscar...",
    "products.filter": "Filtrar",
    "products.all": "Todas as Categorias",
    "products.sort": "Ordenar por",
    "products.sort.newest": "Mais Recentes",
    "products.sort.price_asc": "Preço: Menor para Maior",
    "products.sort.price_desc": "Preço: Maior para Menor",
    "products.empty": "Nenhum produto encontrado",
    "products.add_cart": "Adicionar ao Carrinho",
    "products.in_stock": "Em Estoque",
    "products.out_stock": "Sem Estoque",
    "products.qty": "Quantidade",
    "cart.title": "Carrinho de Compras",
    "cart.empty": "Seu carrinho está vazio",
    "cart.subtotal": "Subtotal",
    "cart.checkout": "Finalizar Compra",
    "cart.remove": "Remover",
    "cart.continue": "Continuar Comprando",
    "orders.title": "Meus Pedidos",
    "orders.empty": "Nenhum pedido ainda",
    "orders.number": "Pedido",
    "orders.status.pending_payment": "Aguardando Pagamento",
    "orders.status.paid": "Pago",
    "orders.status.shipped": "Enviado",
    "orders.status.completed": "Concluído",
    "orders.status.cancelled": "Cancelado",
    "orders.total": "Total",
    "orders.date": "Data",
    "orders.view": "Ver Detalhes",
    "payment.title": "Pagamento",
    "payment.method": "Pagar com USDD",
    "payment.address": "Envie USDD para este endereço",
    "payment.amount": "Valor",
    "payment.confirm": "Já enviei o pagamento",
    "payment.waiting": "Aguardando confirmação...",
    "payment.success": "Pagamento Confirmado!",
    "account.title": "Minha Conta",
    "account.profile": "Perfil",
    "account.addresses": "Endereços",
    "account.orders": "Pedidos",
    "account.save": "Salvar Alterações",
    "account.add_address": "Adicionar Endereço",
    "rates.title": "Taxas de Câmbio ao Vivo",
    "rates.usdd": "1 USDD =",
    "rates.updated": "Atualizado",
    "common.loading": "Carregando...",
    "common.error": "Algo deu errado",
    "common.retry": "Tentar Novamente",
    "common.cancel": "Cancelar",
    "common.save": "Salvar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.close": "Fechar",
    "common.back": "Voltar",
    "common.next": "Próximo",
    "common.confirm": "Confirmar",
    "chat.title": "Suporte ao Cliente",
    "chat.placeholder": "Pergunte sobre produtos, pedidos ou pagamentos...",
    "chat.send": "Enviar",
    "chat.greeting": "Olá! Sou o assistente de IA da Daiizen. Como posso ajudá-lo hoje?",
    "nav.marketplace": "Mercado Global",
    "nav.open_store": "Abrir Loja",
    "nav.influencer": "🌟 Influenciador / KOL",
    "nav.supply_chain": "🏭 Cadeia de Suprimentos",
    "nav.seller_dashboard": "📊 Painel do Vendedor",
    "nav.referral": "Programa de Indicação",
    "nav.my_store": "Minha Loja",
    "marketplace.sort.popular": "Mais Populares",
    "marketplace.sort.newest": "Mais Recentes",
    "marketplace.sort.price_asc": "Preço: Menor para Maior",
    "marketplace.sort.price_desc": "Preço: Maior para Menor",
    "marketplace.category": "Categoria",
    "marketplace.all_categories": "Todas as Categorias",
    "marketplace.price_range": "Faixa de Preço",
    "marketplace.min_price": "Preço Mín.",
    "marketplace.max_price": "Preço Máx.",
    "marketplace.apply": "Aplicar",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.products": "المنتجات",
    "nav.cart": "السلة",
    "nav.account": "الحساب",
    "nav.admin": "الإدارة",
    "nav.login": "تسجيل الدخول",
    "nav.logout": "تسجيل الخروج",
    "nav.search": "ابحث عن المنتجات...",
    "hero.title": "منتجات عالية الجودة،\nأسعار ثابتة",
    "hero.subtitle": "تسوق بعملة USDD المستقرة — قوتك الشرائية محمية من التضخم.",
    "hero.cta": "تسوق الآن",
    "hero.learn": "تعرف على USDD",
    "products.title": "منتجاتنا",
    "products.search": "بحث...",
    "products.filter": "تصفية",
    "products.all": "جميع الفئات",
    "products.sort": "ترتيب حسب",
    "products.sort.newest": "الأحدث",
    "products.sort.price_asc": "السعر: من الأقل للأعلى",
    "products.sort.price_desc": "السعر: من الأعلى للأقل",
    "products.empty": "لم يتم العثور على منتجات",
    "products.add_cart": "أضف إلى السلة",
    "products.in_stock": "متوفر",
    "products.out_stock": "غير متوفر",
    "products.qty": "الكمية",
    "cart.title": "سلة التسوق",
    "cart.empty": "سلتك فارغة",
    "cart.subtotal": "المجموع الفرعي",
    "cart.checkout": "إتمام الشراء",
    "cart.remove": "إزالة",
    "cart.continue": "مواصلة التسوق",
    "orders.title": "طلباتي",
    "orders.empty": "لا توجد طلبات بعد",
    "orders.number": "طلب",
    "orders.status.pending_payment": "في انتظار الدفع",
    "orders.status.paid": "مدفوع",
    "orders.status.shipped": "تم الشحن",
    "orders.status.completed": "مكتمل",
    "orders.status.cancelled": "ملغي",
    "orders.total": "الإجمالي",
    "orders.date": "التاريخ",
    "orders.view": "عرض التفاصيل",
    "payment.title": "الدفع",
    "payment.method": "الدفع بـ USDD",
    "payment.address": "أرسل USDD إلى هذا العنوان",
    "payment.amount": "المبلغ",
    "payment.confirm": "لقد أرسلت الدفعة",
    "payment.waiting": "في انتظار التأكيد...",
    "payment.success": "تم تأكيد الدفع!",
    "account.title": "حسابي",
    "account.profile": "الملف الشخصي",
    "account.addresses": "العناوين",
    "account.orders": "الطلبات",
    "account.save": "حفظ التغييرات",
    "account.add_address": "إضافة عنوان",
    "rates.title": "أسعار الصرف المباشرة",
    "rates.usdd": "1 USDD =",
    "rates.updated": "تم التحديث",
    "common.loading": "جار التحميل...",
    "common.error": "حدث خطأ ما",
    "common.retry": "حاول مجدداً",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.close": "إغلاق",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.confirm": "تأكيد",
    "chat.title": "دعم العملاء",
    "chat.placeholder": "اسأل عن المنتجات أو الطلبات أو المدفوعات...",
    "chat.send": "إرسال",
    "chat.greeting": "مرحباً! أنا مساعد الذكاء الاصطناعي لـ Daiizen. كيف يمكنني مساعدتك اليوم؟",
    "nav.marketplace": "السوق العالمي",
    "nav.open_store": "افتح متجراً",
    "nav.influencer": "🌟 مؤثر / KOL",
    "nav.supply_chain": "🏭 سلسلة التوريد",
    "nav.seller_dashboard": "📊 لوحة البائع",
    "nav.referral": "مكافآت الإحالة",
    "nav.my_store": "متجري",
    "marketplace.sort.popular": "الأكثر شعبية",
    "marketplace.sort.newest": "الأحدث",
    "marketplace.sort.price_asc": "السعر: من الأقل للأعلى",
    "marketplace.sort.price_desc": "السعر: من الأعلى للأقل",
    "marketplace.category": "الفئة",
    "marketplace.all_categories": "جميع الفئات",
    "marketplace.price_range": "نطاق السعر",
    "marketplace.min_price": "أدنى سعر",
    "marketplace.max_price": "أعلى سعر",
    "marketplace.apply": "تطبيق",
  },
  ru: {
    "nav.home": "Главная",
    "nav.products": "Товары",
    "nav.cart": "Корзина",
    "nav.account": "Аккаунт",
    "nav.admin": "Админ",
    "nav.login": "Войти",
    "nav.logout": "Выйти",
    "nav.search": "Поиск товаров...",
    "hero.title": "Качественные Товары,\nСтабильные Цены",
    "hero.subtitle": "Покупайте за USDD — ваша покупательная способность защищена от инфляции.",
    "hero.cta": "Купить Сейчас",
    "hero.learn": "Узнать о USDD",
    "products.title": "Наши Товары",
    "products.search": "Поиск...",
    "products.filter": "Фильтр",
    "products.all": "Все Категории",
    "products.sort": "Сортировка",
    "products.sort.newest": "Новинки",
    "products.sort.price_asc": "Цена: по возрастанию",
    "products.sort.price_desc": "Цена: по убыванию",
    "products.empty": "Товары не найдены",
    "products.add_cart": "В Корзину",
    "products.in_stock": "В наличии",
    "products.out_stock": "Нет в наличии",
    "products.qty": "Количество",
    "cart.title": "Корзина",
    "cart.empty": "Ваша корзина пуста",
    "cart.subtotal": "Итого",
    "cart.checkout": "Оформить Заказ",
    "cart.remove": "Удалить",
    "cart.continue": "Продолжить Покупки",
    "orders.title": "Мои Заказы",
    "orders.empty": "Заказов пока нет",
    "orders.number": "Заказ",
    "orders.status.pending_payment": "Ожидает Оплаты",
    "orders.status.paid": "Оплачен",
    "orders.status.shipped": "Отправлен",
    "orders.status.completed": "Завершён",
    "orders.status.cancelled": "Отменён",
    "orders.total": "Итого",
    "orders.date": "Дата",
    "orders.view": "Подробнее",
    "payment.title": "Оплата",
    "payment.method": "Оплатить USDD",
    "payment.address": "Отправьте USDD на этот адрес",
    "payment.amount": "Сумма",
    "payment.confirm": "Я отправил платёж",
    "payment.waiting": "Ожидание подтверждения...",
    "payment.success": "Платёж Подтверждён!",
    "account.title": "Мой Аккаунт",
    "account.profile": "Профиль",
    "account.addresses": "Адреса",
    "account.orders": "Заказы",
    "account.save": "Сохранить Изменения",
    "account.add_address": "Добавить Адрес",
    "rates.title": "Курсы Валют в Реальном Времени",
    "rates.usdd": "1 USDD =",
    "rates.updated": "Обновлено",
    "common.loading": "Загрузка...",
    "common.error": "Что-то пошло не так",
    "common.retry": "Попробовать снова",
    "common.cancel": "Отмена",
    "common.save": "Сохранить",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.close": "Закрыть",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.confirm": "Подтвердить",
    "chat.title": "Служба поддержки",
    "chat.placeholder": "Спросите о товарах, заказах или оплате...",
    "chat.send": "Отправить",
    "chat.greeting": "Привет! Я ИИ-ассистент Daiizen. Чем могу помочь?",
    "nav.marketplace": "Глобальный Рынок",
    "nav.open_store": "Открыть Магазин",
    "nav.influencer": "🌟 Инфлюенсер / KOL",
    "nav.supply_chain": "🏭 Цепочка Поставок",
    "nav.seller_dashboard": "📊 Кабинет Продавца",
    "nav.referral": "Реферальные Награды",
    "nav.my_store": "Мой Магазин",
    "marketplace.sort.popular": "Популярные",
    "marketplace.sort.newest": "Новинки",
    "marketplace.sort.price_asc": "Цена: по возрастанию",
    "marketplace.sort.price_desc": "Цена: по убыванию",
    "marketplace.category": "Категория",
    "marketplace.all_categories": "Все Категории",
    "marketplace.price_range": "Ценовой Диапазон",
    "marketplace.min_price": "Мин. цена",
    "marketplace.max_price": "Макс. цена",
    "marketplace.apply": "Применить",
  },
  zh: {
    // Nav
    "nav.home": "首页",
    "nav.products": "商品",
    "nav.cart": "购物车",
    "nav.account": "账户",
    "nav.admin": "管理后台",
    "nav.login": "登录",
    "nav.logout": "退出",
    "nav.search": "搜索商品...",
    "nav.marketplace": "全球商城",
    "nav.open_store": "开店入驻",
    "nav.influencer": "🌟 网红 / KOL",
    "nav.supply_chain": "🏭 供应链 / 品牌",
    "nav.seller_dashboard": "📊 卖家后台",
    "nav.referral": "推荐奖励",
    "nav.my_store": "我的店铺",
    // Hero
    "hero.title": "全球好货，\n稳定价格",
    "hero.subtitle": "使用 USDD 稳定币购物，您的购买力免受通货膨胀影响。",
    "hero.cta": "立即购物",
    "hero.learn": "了解 USDD",
    // Products
    "products.title": "精选商品",
    "products.search": "搜索...",
    "products.filter": "筛选",
    "products.all": "全部分类",
    "products.sort": "排序",
    "products.sort.newest": "最新上架",
    "products.sort.price_asc": "价格从低到高",
    "products.sort.price_desc": "价格从高到低",
    "products.empty": "暂无商品",
    "products.add_cart": "加入购物车",
    "products.in_stock": "有货",
    "products.out_stock": "缺货",
    "products.qty": "数量",
    // Cart
    "cart.title": "购物车",
    "cart.empty": "购物车为空",
    "cart.subtotal": "小计",
    "cart.checkout": "去结算",
    "cart.remove": "删除",
    "cart.continue": "继续购物",
    // Checkout
    "checkout.title": "结算",
    "checkout.address": "收货地址",
    "checkout.payment": "支付方式",
    "checkout.place_order": "提交订单",
    "checkout.total": "总计",
    // Orders
    "orders.title": "我的订单",
    "orders.empty": "暂无订单",
    "orders.status.pending": "待处理",
    "orders.status.processing": "处理中",
    "orders.status.shipped": "已发货",
    "orders.status.delivered": "已送达",
    "orders.status.cancelled": "已取消",
    // Account
    "account.title": "我的账户",
    "account.profile": "个人资料",
    "account.orders": "订单记录",
    "account.settings": "设置",
    // Login
    "login.title": "登录账户",
    "login.subtitle": "选择您的登录方式",
    "login.google": "使用 Google 登录",
    "login.or": "或使用以下方式",
    "login.phone": "手机号",
    "login.email": "邮箱",
    "login.phone_number": "手机号码",
    "login.send_code": "发送验证码",
    "login.verify_code": "验证码",
    "login.verify": "验证",
    "login.email_addr": "邮箱地址",
    "login.password": "密码",
    "login.signin": "登录",
    "login.no_account": "没有账户？",
    "login.signup": "注册",
    "login.have_account": "已有账户？",
    "login.name": "姓名",
    "login.confirm_password": "确认密码",
    "login.create_account": "创建账户",
    "login.terms": "登录即表示您同意我们的",
    "login.terms_link": "服务条款",
    "login.privacy_link": "隐私政策",
    "login.and": "和",
    // Rates
    "rates.usdd": "1 USDD =",
    "rates.updated": "更新时间",
    // Common
    "common.loading": "加载中...",
    "common.error": "出错了",
    "common.retry": "重试",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.close": "关闭",
    "common.back": "返回",
    "common.next": "下一步",
    "common.confirm": "确认",
    // Chat
    "chat.title": "客服支持",
    "chat.placeholder": "询问商品、订单或支付相关问题...",
    "chat.send": "发送",
    "chat.greeting": "您好！我是 Daiizen 的 AI 助手，有什么可以帮您？",
    // Marketplace
    "marketplace.title": "全球商城",
    "marketplace.subtitle": "发现来自全球卖家的优质商品",
    "marketplace.search": "搜索商品或店铺...",
    "marketplace.search_stores": "按店铺名称搜索...",
    "marketplace.products": "商品",
    "marketplace.stores": "店铺",
    "marketplace.all_platforms": "全部平台",
    "marketplace.no_products": "暂无商品",
    "marketplace.try_other": "尝试其他关键词",
    "marketplace.no_stores": "暂无店铺",
    "marketplace.prev": "上一页",
    "marketplace.next": "下一页",
    "marketplace.page_of": "第 {page} 页 / 共 {total} 页",
    "marketplace.open_store_cta": "想在 Daiizen 开店？",
    "marketplace.open_store_desc": "支持导入 TikTok、Amazon 等平台商品，轻松触达全球买家。",
    "marketplace.open_store_btn": "立即开店",
    "marketplace.platform.all": "全部平台",
    "marketplace.platform.pinduoduo": "拼多多",
    "marketplace.platform.xiaohongshu": "小红书",
    "marketplace.platform.taobao": "淘宝",
    "marketplace.platform.jd": "京东",
    "marketplace.platform.other": "其他",
    "marketplace.sort.popular": "最热销",
    "marketplace.sort.newest": "最新上架",
    "marketplace.sort.price_asc": "价格从低到高",
    "marketplace.sort.price_desc": "价格从高到低",
    "marketplace.category": "分类",
    "marketplace.all_categories": "全部分类",
    "marketplace.price_range": "价格区间",
    "marketplace.min_price": "最低价",
    "marketplace.max_price": "最高价",
    "marketplace.apply": "应用",
    // Referral
    "referral.title": "推荐奖励中心",
    "referral.subtitle": "邀请好友注册并完成首单，最多享受 3 层推荐奖励（L1: 5% / L2: 2% / L3: 1%）",
    "referral.login_title": "登录后查看推荐奖励",
    "referral.login_desc": "邀请好友注册购物，最多享受3层推荐奖励",
    "referral.login_btn": "立即登录 / 注册",
    "referral.balance": "可用余额 (USDD)",
    "referral.total_earned": "累计奖励 (USDD)",
    "referral.total_referrals": "推荐总人数",
    "referral.pending_rewards": "待确认奖励",
    "referral.my_link": "我的专属推荐链接",
    "referral.link_desc": "分享给好友，好友完成首单后您即可获得奖励",
    "referral.copy": "复制",
    "referral.copied": "✓ 已复制",
    "referral.code": "推荐码：",
    "referral.rules_title": "奖励规则",
    "referral.l1": "L1 直接推荐",
    "referral.l1_desc": "您直接邀请的好友完成首单",
    "referral.l2": "L2 二级推荐",
    "referral.l2_desc": "您的好友邀请的人完成首单",
    "referral.l3": "L3 三级推荐",
    "referral.l3_desc": "三级关系人完成首单（最深3层）",
    "referral.rules_note": "* 奖励仅在被推荐人完成首次购物时触发，仅限3层，无多级传导。奖励以平台积分（USDD）发放，可用于抵扣购物或申请提现。",
    "referral.tree_tab": "推荐树",
    "referral.rewards_tab": "奖励记录",
    "referral.direct": "直接推荐",
    "referral.second": "二级推荐",
    "referral.third": "三级推荐",
    "referral.no_direct": "暂无直接推荐，分享您的链接开始邀请！",
    "referral.no_second": "暂无二级推荐",
    "referral.no_third": "暂无三级推荐",
    "referral.user": "用户",
    "referral.purchased": "已购物",
    "referral.not_purchased": "未购物",
    "referral.no_rewards": "暂无奖励记录",
    "referral.no_rewards_desc": "邀请好友完成首单后，奖励将在此显示",
    "referral.from_user": "来自 #{id} 号用户首单",
    "referral.status.pending": "待确认",
    "referral.status.confirmed": "已确认",
    "referral.status.paid": "已发放",
    "referral.status.cancelled": "已取消",
    "referral.copied_toast": "推荐链接已复制！",
    // Onboarding shared
    "onboarding.login_title": "登录后开始入驻",
    "onboarding.login_btn": "立即登录 / 注册",
    "onboarding.already_store": "您已有店铺",
    "onboarding.store_name_label": "店铺名称：",
    "onboarding.active": "已激活",
    "onboarding.pending": "审核中",
    "onboarding.go_seller": "进入卖家后台",
    "onboarding.browse": "浏览商城",
    "onboarding.deposit_title": "缴纳开店保证金",
    "onboarding.no_deposit": "✅ 当前无需缴纳保证金，直接提交审核",
    "onboarding.deposit_amount": "保证金金额",
    "onboarding.deposit_note": "保证金用于保障平台交易安全，正常经营退出时全额退还。",
    "onboarding.payment_method": "支付方式：USDD TRC-20",
    "onboarding.deposit_instruction": "请向上方地址转账 {amount} USDD，转账后填写交易哈希",
    "onboarding.txhash_label": "交易哈希 (TxHash)",
    "onboarding.txhash_placeholder": "TRC20 交易哈希",
    "onboarding.submitting": "提交中...",
    "onboarding.submit_deposit": "提交保证金，等待审核",
    "onboarding.submit_apply": "提交申请",
    "onboarding.submitted_title": "申请已提交！",
    "onboarding.prev": "上一步",
    "onboarding.next": "下一步",
    "onboarding.next_deposit": "下一步：缴纳保证金",
    // Influencer onboarding
    "influencer.login_desc": "成为 Daiizen 网红卖家，连接全球供应链",
    "influencer.title": "网红卖家入驻",
    "influencer.subtitle": "连接全球供应链，零库存开店，AI 选品助力爆款",
    "influencer.step0": "选择类型",
    "influencer.step1": "店铺信息",
    "influencer.step2": "社媒资料",
    "influencer.step3": "缴纳保证金",
    "influencer.step4": "完成",
    "influencer.choose_type": "选择入驻类型",
    "influencer.kol_title": "网红 / KOL 入驻",
    "influencer.kol_desc": "有粉丝基础，想通过带货变现。从供应链选品，零库存，AI 助力爆款选品。",
    "influencer.kol_badge1": "零库存",
    "influencer.kol_badge2": "AI 选品",
    "influencer.kol_badge3": "代发货",
    "influencer.sc_title": "供应链 / 品牌入驻",
    "influencer.sc_desc": "有货源，想通过网红渠道扩大销量。提供批发目录，由网红代销。",
    "influencer.sc_badge1": "批发目录",
    "influencer.sc_badge2": "网红代销",
    "influencer.sc_badge3": "一件代发",
    "influencer.store_info": "填写店铺信息",
    "influencer.store_name": "店铺名称 *",
    "influencer.store_name_placeholder": "例如：小红的好物分享",
    "influencer.store_slug": "店铺英文标识 (slug) *",
    "influencer.store_slug_placeholder": "例如：xiaohong-shop（只能包含字母、数字、横线）",
    "influencer.store_url_preview": "店铺链接：/store/",
    "influencer.store_desc_label": "店铺简介",
    "influencer.store_desc_placeholder": "介绍你的店铺风格和主营品类...",
    "influencer.contact_email": "联系邮箱",
    "influencer.social_title": "填写社媒账号（选填）",
    "influencer.social_desc": "填写您的社交媒体账号，有助于提高店铺可信度和曝光率",
    "influencer.tiktok": "🎵 TikTok / 抖音",
    "influencer.instagram": "📸 Instagram",
    "influencer.youtube": "▶️ YouTube",
    "influencer.xiaohongshu": "📕 小红书",
    "influencer.followers": "粉丝总量（约）",
    "influencer.followers_placeholder": "例如：50000",
    "influencer.submitted_desc": "您的网红店铺申请已提交，平台将在 1-3 个工作日内完成审核。审核通过后，您即可开始从供应链选品、发布商品。",
    "influencer.benefit1_title": "零库存开店",
    "influencer.benefit1_desc": "从供应链直接选品，无需囤货，代发货到买家",
    "influencer.benefit2_title": "AI 智能选品",
    "influencer.benefit2_desc": "AI 分析爆款趋势，为你的粉丝群体推荐最合适的商品",
    "influencer.benefit3_title": "3级裂变奖励",
    "influencer.benefit3_desc": "邀请好友注册购物，最多享受3层推荐奖励，持续增收",
    // Supply chain onboarding
    "supplychain.login_desc": "成为 Daiizen 供应链合作伙伴，连接全球网红渠道",
    "supplychain.title": "供应链 / 品牌入驻",
    "supplychain.subtitle": "上传批发商品目录，让全球网红帮您带货，一件代发，轻松扩销",
    "supplychain.step0": "基本信息",
    "supplychain.step1": "供应链资料",
    "supplychain.step2": "缴纳保证金",
    "supplychain.step3": "完成",
    "supplychain.basic_info": "填写基本信息",
    "supplychain.company_name": "公司 / 品牌名称 *",
    "supplychain.company_name_placeholder": "例如：义乌好货批发",
    "supplychain.company_desc": "公司简介",
    "supplychain.company_desc_placeholder": "介绍您的主营品类、产品优势...",
    "supplychain.contact_email": "联系邮箱",
    "supplychain.contact_phone": "联系电话",
    "supplychain.country": "公司所在国家/地区",
    "supplychain.country_placeholder": "例如：China",
    "supplychain.details_title": "供应链详情",
    "supplychain.warehouse": "仓库所在地",
    "supplychain.warehouse_placeholder": "例如：China - Yiwu",
    "supplychain.shipping_days": "平均发货天数",
    "supplychain.moq": "最小起订量（件）",
    "supplychain.moq_placeholder": "1（代发填1）",
    "supplychain.moq_note": "如支持一件代发，请填写 1",
    "supplychain.dropship_title": "🤝 代发合作说明",
    "supplychain.dropship_desc": "入驻后您可上传批发商品目录（含批发底价）。网红选品后以自定义价格销售，订单产生时平台通知您直接发货给买家。平台从每笔销售中抽取手续费，供应链收取批发底价，网红赚取差价利润。",
    "supplychain.submitted_desc": "您的供应链店铺申请已提交，平台将在 1-3 个工作日内完成审核。审核通过后，您即可上传商品批发目录，开始与网红合作。",
    "supplychain.benefit1_title": "全球网红渠道",
    "supplychain.benefit1_desc": "接入平台网红资源，快速打开海外市场，无需自建销售团队",
    "supplychain.benefit2_title": "一件代发",
    "supplychain.benefit2_desc": "网红卖出即通知发货，无需网红囤货，降低双方库存风险",
    "supplychain.benefit3_title": "稳定批发收入",
    "supplychain.benefit3_desc": "每笔销售收取批发底价，平台负责收款结算，资金安全有保障",
    // Review
    "review.title": "买家评价",
    "review.no_reviews": "暂无评价，成为第一个评价的人！",
    "review.write": "撰写评价",
    "review.rating": "评分",
    "review.comment": "评论（可选）",
    "review.submit": "提交评价",
    "review.submitting": "提交中...",
    "review.success": "评价已提交！",
    "review.already": "已评价",
    // Store Product Detail
    "storeproduct.from": "来自",
    "storeproduct.units": "件",
    "storeproduct.description": "商品详情",
    "storeproduct.buy_on": "在以下平台购买",
    "storeproduct.redirect_note": "此商品将跳转到原始平台完成购买",
    "storeproduct.view_more": "查看该店更多商品",
    "storeproduct.enter_store": "进入店铺",
    // Seller Dashboard
    "seller.open_store": "开设您的店铺",
    "seller.open_store_desc": "在 Daiizen 全球市场开店，触达全球买家",
    "seller.notice_title": "开店须知",
    "seller.deposit_required": "需缴保证金",
    "seller.deposit_refundable": "，退店时可退还",
    "seller.platform_fee": "平台收取",
    "seller.fee_per_order": "手续费（每笔成交）",
    "seller.review_required": "店铺需经管理员审核后方可营业",
    "seller.import_note": "支持导入 TikTok、拼多多、小红书、Amazon、SHEIN 等平台商品链接",
    "seller.store_name": "店铺名称 *",
    "seller.store_desc": "店铺简介",
    "seller.contact_email": "联系邮筱",
    "seller.contact_phone": "联系电话",
    "seller.country": "所在国家/地区",
    "seller.deposit_confirmed": "保证金已确认",
    "seller.deposit_pending": "保证金待确认",
    "seller.pay_deposit": "缴店铺保证金",
    "seller.deposit_address": "USDD TRC-20 收款地址：",
    "seller.txhash": "交易哈希 (TxHash)",
    "seller.no_products": "还没有商品，点击上方按鈕添加",
    "seller.prev_page": "上一页",
    "seller.next_page": "下一页",
    "seller.add_product": "添加商品",
    "seller.manual_add": "手动添加",
    "seller.import_link": "导入链接",
    "seller.product_name": "商品名称 *",
    "seller.product_desc": "商品描述",
    "seller.price_usdd": "价格 (USDD) *",
    "seller.stock": "库存数量",
    "seller.image_urls": "商品图片 URL（每行一个）",
    "seller.product_link": "商品链接 *",
    "seller.import_placeholder": "粘贴商品链接，如 https://www.tiktok.com/...",
    "seller.import_platforms": "支持 TikTok、拼多多、小红书、Amazon、SHEIN、淘宝、京东、Lazada、Shopee 等平台",
    "seller.ai_parsing": "AI 正在解析商品信息...",
    "seller.ai_note": "AI 将自动提取商品名称、描述、价格等信息，您可在导入后编辑",
    "seller.login_required": "请先登录",
    "seller.login_desc": "登录后即可开设您的店铺",
    "seller.back_home": "返回首页",
    "seller.view_store": "查看店铺主页",
    "seller.under_review": "店铺审核中",
    "seller.review_desc": "您的开店申请正在审核中。请先缴纳保证金，管理员确认后将尽快审核您的申请。",
    "seller.rejected": "申请已被拒绝",
    "seller.suspended": "店铺已被暂停",
    "seller.products_on_sale": "在售商品",
    "seller.total_orders": "总订单",
    "seller.total_earnings": "总收益",
    "seller.withdraw_btn": "申请提现 →",
    "seller.platform_fee_label": "平台手续费",
    "seller.products_tab": "商品管理",
    "seller.settings_tab": "店铺设置",
    "seller.deposit_tab": "保证金",
    "seller.store_info": "店铺基本信息",
    "seller.store_name_label": "店铺名称",
    "seller.store_logo": "店铺 Logo URL",
    "seller.store_banner": "店铺横幅 URL",
    "seller.status.pending": "审核中",
    "seller.status.active": "已开业",
    "seller.status.suspended": "已暂停",
    "seller.status.rejected": "已拒绝",
    // Admin
    "admin.pending_stores": "待审核店铺",
    "admin.no_pending": "暂无待审核店铺",
    "admin.col_store": "店铺",
    "admin.col_seller": "卖家",
    "admin.col_applied": "申请时间",
    "admin.col_actions": "操作",
    "admin.approve": "通过",
    "admin.reject": "拒绝",
    "admin.all_stores": "全部店铺",
    "admin.col_status": "状态",
    "admin.col_products": "商品数",
    "admin.suspend": "暂停",
    "admin.restore": "恢复",
    "admin.deposit_mgmt": "保证金管理",
    "admin.no_deposits": "暂无待确认保证金",
    "admin.col_amount": "金额",
    "admin.col_txhash": "交易哈希",
    "admin.confirm_deposit": "确认收款",
    "admin.market_config": "市场平台配置",
    "admin.wallet_address": "收款钉包地址（USDD TRC-20）",
    "admin.payment_config": "收款方式配置",
    "admin.payment_config_desc": "配置支付宝、微信、銀联收款账户，卖家缴交保证金时将看到这些账户信息",
    "admin.configured_methods": "已配置收款方式",
    "admin.delete": "删除",
    "admin.add_payment": "添加/更新收款方式",
    "admin.payment_type": "支付方式",
    "admin.alipay": "支付宝",
    "admin.wechat": "微信支付",
    "admin.unionpay": "銀联转账",
    "admin.account_name": "收款人姓名 / 商户名",
    "admin.account_number": "手机号 / 账号",
    "admin.qr_url": "收款二维码 URL（可选）",
    "admin.enable_method": "启用此收款方式",
    "admin.usdd_deposits": "USDD 充値审核",
    "admin.usdd_deposits_desc": "用户提交充値申请后需要管理员手动确认，确认后余额自动更新。",
    "admin.no_usdd_deposits": "暂无待审核充値申请",
    "admin.confirm_deposit_btn": "✓ 确认充値",
    "admin.reject_deposit_btn": "✗ 拒绝",
    "admin.withdrawals": "卖家提现管理",
    "admin.no_withdrawals": "暂无提现申请",
    "admin.approve_withdrawal": "✓ 批准",
    "admin.confirm_paid": "确认支付",
    "admin.cancel": "取消",
    "admin.mark_paid": "💸 标记已支付",
    "admin.tab_stores": "店铺管理",
    "admin.tab_deposit": "保证金",
    "admin.tab_market": "市场配置",
    "admin.tab_payment": "收款配置",
    "admin.tab_usdd": "USDD充値审核",
    "admin.tab_withdrawals": "卖家提现",
    "admin.reject_reason": "拒绝原因（可选）",
    "admin.suspend_reason": "暂停原因",
    "admin.deposit_confirmed_toast": "充値已确认，余额已更新",
    "admin.deposit_rejected_toast": "充値已拒绝",
    "admin.withdrawal_approved_toast": "提现已批准",
    "admin.withdrawal_rejected_toast": "提现已拒绝，余额已退回",
    "admin.withdrawal_paid_toast": "已标记为已支付",
    "admin.payment_updated_toast": "收款方式已更新",
    "admin.deleted_toast": "已删除",
    "admin.store_approved_toast": "店铺已通过",
    "admin.store_rejected_toast": "店铺已拒绝",
    "admin.store_suspended_toast": "店铺已暂停",
    "admin.store_restored_toast": "店铺已恢复",
    "admin.deposit_confirmed2_toast": "保证金已确认",
    "admin.deposit_rejected2_toast": "已拒绝保证金",
    "admin.config_updated_toast": "配置已更新",
    // Wallet
    "wallet.title": "USDD 钉包",
    "wallet.balance": "可用余额",
    "wallet.deposit": "充値",
    "wallet.history": "交易记录",
    "wallet.no_transactions": "暂无交易记录",
    "wallet.deposit_title": "充値 USDD",
    "wallet.deposit_desc": "将 USDD（TRC-20 / TRON 网络）转账到以下地址",
    "wallet.network_warning": "⚠️ 仅支持 TRC-20 / TRON 网络的 USDD，请勿发错币种或网络，否则资金将永久丢失。",
    "wallet.copy_address": "复制地址",
    "wallet.copied": "已复制！",
    "wallet.submit_deposit": "提交充値凭证",
    "wallet.submit_desc": "转账后，提交交易哈希由管理员确认",
    "wallet.txhash_label": "交易哈希 (TxHash)",
    "wallet.txhash_placeholder": "如 abc123...",
    "wallet.amount_label": "充値金额 (USDD)",
    "wallet.submit_btn": "提交审核",
    "wallet.submitting": "提交中...",
    "wallet.submitted_toast": "充値已提交！管理员将在 24 小时内确认。",
    "wallet.login_required": "请登录后查看钉包",
    // Withdrawal
    "withdrawal.title": "卖家提现",
    "withdrawal.balance": "可提现余额",
    "withdrawal.request": "申请提现",
    "withdrawal.history": "提现记录",
    "withdrawal.no_history": "暂无提现记录",
    "withdrawal.amount": "提现金额 (USDD)",
    "withdrawal.wallet": "收款钉包（TRC-20）",
    "withdrawal.wallet_placeholder": "USDD TRC-20 钉包地址",
    "withdrawal.note": "备注（可选）",
    "withdrawal.submit": "提交提现申请",
    "withdrawal.submitting": "提交中...",
    "withdrawal.success": "提现申请已提交！",
    "withdrawal.insufficient": "余额不足",
    "withdrawal.login_required": "请先登录",
    "withdrawal.no_store": "您需要有店铺才能提现收益",
    "withdrawal.status.pending": "待审核",
    "withdrawal.status.approved": "已批准",
    "withdrawal.status.rejected": "已拒绝",
    "withdrawal.status.paid": "已打款",
    // Common extra
    "common.coming_soon": "即将推出",
    "common.saving": "保存中...",
    "common.saved": "已保存！",
    "common.submit": "提交",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.sort": "排序",
    "common.all": "全部",
    "common.yes": "是",
    "common.no": "否",
    "common.na": "无",
    "common.date": "日期",
    "common.amount": "金额",
    "common.status": "状态",
    "common.actions": "操作",
    "common.user": "用户",
    "common.store": "店铺",
    "common.product": "商品",
    "common.order": "订单",
    "common.price": "价格",
    "common.qty": "数量",
    "common.total": "总计",
    "common.note": "备注",
    "common.reason": "原因",
    "common.txhash": "交易哈希",
    "common.wallet_address": "钉包地址",
    "common.copy": "复制",
    "common.copied": "已复制！",
    "common.sign_in": "登录",
    "common.sign_up": "注册",
    "common.email": "邮筱",
    "common.phone": "手机号",
    "common.password": "密码",
    "common.name": "姓名",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("daiizen-lang");
    return (saved as Language) || "en";
  });

  const currentLang = LANGUAGES.find((l) => l.code === language)!;

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("daiizen-lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = currentLang.dir;
  }, [language, currentLang.dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir: currentLang.dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
